In [ ]:
!pip install datasets
!pip uninstall -y transformers accelerate
!pip install transformers accelerate

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting datasets
  Downloading datasets-2.12.0-py3-none-any.whl (474 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 474.6/474.6 kB 10.4 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (1.22.4)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (9.0.0)
Collecting dill<0.3.7,>=0.3.0 (from datasets)
  Downloading dill-0.3.6-py3-none-any.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 17.0 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (1.5.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (2.27.1)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.65.0)
Collecting xxhash (from datasets)
  Downloading xxhash-3.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.5/212.5 kB 24.9 MB/s eta 0:00:00
Collecting multiprocess (from datasets)
  Downloading multiprocess-0.70.14-py310-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.3/134.3 kB 17.9 MB/s eta 0:00:00
Requirement already satisfied: fsspec[http]>=2021.11.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (2023.4.0)
Collecting aiohttp (from datasets)
  Downloading aiohttp-3.8.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 39.4 MB/s eta 0:00:00
Collecting huggingface-hub<1.0.0,>=0.11.0 (from datasets)
  Downloading huggingface_hub-0.15.1-py3-none-any.whl (236 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 236.8/236.8 kB 26.9 MB/s eta 0:00:00
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (23.1)
Collecting responses<0.19 (from datasets)
  Downloading responses-0.18.0-py3-none-any.whl (38 kB)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (2.0.12)
Collecting multidict<7.0,>=4.5 (from aiohttp->datasets)
  Downloading multidict-6.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 14.0 MB/s eta 0:00:00
Collecting async-timeout<5.0,>=4.0.0a3 (from aiohttp->datasets)
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp->datasets)
  Downloading yarl-1.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (268 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 26.9 MB/s eta 0:00:00
Collecting frozenlist>=1.1.1 (from aiohttp->datasets)
  Downloading frozenlist-1.3.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (149 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.6/149.6 kB 19.9 MB/s eta 0:00:00
Collecting aiosignal>=1.1.2 (from aiohttp->datasets)
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets) (3.12.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets) (4.5.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->datasets) (3.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->datasets) (1.16.0)
Installing collected packages: xxhash, multidict, frozenlist, dill, async-timeout, yarl, responses, multiprocess, huggingface-hub, aiosignal, aiohttp, datasets
Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 datasets-2.12.0 dill-0.3.6 frozenlist-1.3.3 huggingface-hub-0.15.1 multidict-6.0.4 multiprocess-0.70.14 responses-0.18.0 xxhash-3.2.0 yarl-1.9.2
WARNING: Skipping transformers as it is not installed.
WARNING: Skipping accelerate as it is not installed.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting transformers
  Downloading transformers-4.29.2-py3-none-any.whl (7.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 59.4 MB/s eta 0:00:00
Collecting accelerate
  Downloading accelerate-0.19.0-py3-none-any.whl (219 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 219.1/219.1 kB 27.2 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.12.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.15.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.22.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2022.10.31)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.27.1)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1 (from transformers)
  Downloading tokenizers-0.13.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 117.0 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.65.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (2.0.1+cu118)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers) (2023.4.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers) (4.5.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->accelerate) (1.11.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->accelerate) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->accelerate) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->accelerate) (2.0.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.6.0->accelerate) (3.25.2)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.6.0->accelerate) (16.0.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.6.0->accelerate) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.6.0->accelerate) (1.3.0)
Installing collected packages: tokenizers, transformers, accelerate
Successfully installed accelerate-0.19.0 tokenizers-0.13.3 transformers-4.29.2

In [ ]:
from transformers import BertTokenizer, BertForSequenceClassification, TrainingArguments, Trainer, AutoModelForSequenceClassification, AutoTokenizer, EarlyStoppingCallback, TextClassificationPipeline

In [ ]:
tokenizer = BertTokenizer.from_pretrained('jhgan/ko-sroberta-multitask')
model = BertForSequenceClassification.from_pretrained("jhgan/ko-sroberta-multitask")
# text = "Replace me by any text you'd like."
# encoded_input = tokenizer(text, return_tensors='pt')
# output = model(**encoded_input)

Downloading (…)solve/main/vocab.txt:   0%|          | 0.00/248k [00:00<?, ?B/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/156 [00:00<?, ?B/s]

Downloading (…)okenizer_config.json:   0%|          | 0.00/585 [00:00<?, ?B/s]

Downloading (…)lve/main/config.json:   0%|          | 0.00/744 [00:00<?, ?B/s]

You are using a model of type roberta to instantiate a model of type bert. This is not supported for all configurations of models and can yield errors.

Downloading pytorch_model.bin:   0%|          | 0.00/443M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at jhgan/ko-sroberta-multitask and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
import pandas as pd
import torch
from datasets import load_metric

In [ ]:
open('안유진.txt', 'r',encoding='utf-8').read()[:100]

'document\tlabel\n"화성시, 도민체전 사전경기서 1부 선두 질주"\t0\n전날 여자부 접영 100m 결승에서 1분00초52로 금메달을 획득한 이근희는 이날 여자부 접영 50m'

In [ ]:
import pandas as pd
import numpy as np

# CSV 파일 읽기
data = pd.read_csv('안유진.txt',sep='\t')
data = data.dropna()

# 데이터 인덱스 리스트 생성
indices = np.arange(len(data))

# train set과 test set 분할
train_indices = np.random.choice(indices, size=int(0.8 * len(data)), replace=False)
test_indices = np.setdiff1d(indices, train_indices)

# train set과 test set 생성
train_set = data.iloc[train_indices]
test_set = data.iloc[test_indices]

In [ ]:
# train set 확인
print(train_set.shape)
print(train_set.head())

(4570, 2)
                                               document  label
1059  이은지는 “언니 잘 됐다”를 안유진, 이영지, 미미의 성대모사로 전해 주위를 폭소케...    1.0
5653  거다 안유진.....유진씨...유진아아아....... 어쩌자고 그리 어여쁘냐.......    1.0
1046      [SC현장] 아이브X르세라핌 기다릴 것…가요광장 DJ 이은지, 통통 튀는 인...    0.0
244                   경기체고 박선우·이서진, 동아수영대회에서 나란히 금메달 획득    0.0
5660                       아이즈원 - 라비앙로즈 뮤비 움짤/ 장원영, 안유진    1.0

In [ ]:
# test set 확인
print(test_set.shape)
print(test_set.head())

(1143, 2)
                                             document  label
8                                ‘K-909’ 아이브, 치명적인 변신    1.0
11  안유진은 설계자 콘셉트로 색다른 스타일을 선보였고, 먼저 ‘일레븐과 러브 다이브’ ...    1.0
17  아이브(안유진·가을·레이·장원영·리즈·이서)가 오직 K-909만을 위한 무대를 선물...    1.0
18                   K-909 아이브, 치명적 변신…골든디스크 무대 최초 공개    1.0
24                 아이브, 오늘(6일) K-909 출격‥골든디스크 무대 첫 공개    1.0

- Train-test split

In [ ]:
# from skmultilearn.model_selection import iterative_train_test_split ### For multi-label split
# X_val, val_labels, X_test, test_labels = iterative_train_test_split(X_test, test_labels, test_size = 0.5)
# from sklearn.model_selection import train_test_split

- Tokeninzing

In [ ]:
train_ = train_set['document'].to_list()[:15000]
# train_ = ratings_train['document'].to_list()
train_label = train_set['label'].to_numpy()[:15000]
# train_label = ratings_train['label'].to_numpy()

In [ ]:
train_data  = tokenizer(train_, return_tensors='pt', truncation = True, padding = True)

In [ ]:
test_ = test_set['document'].to_list()[:5000]
test_data  = tokenizer(test_, return_tensors='pt', truncation=True, padding=True)
test_label = test_set['label'].to_numpy()[:5000]

In [ ]:
from torch.utils.data import Dataset
class PrepDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encoding = encodings
        self.labels = labels

    def __getitem__(self, idx):
        data = {key: val[idx] for key, val in self.encoding.items()}
        data['labels'] = torch.tensor(self.labels[idx]).long()
        return data

    def __len__(self):
        return len(self.labels)

In [ ]:
train = PrepDataset(train_data, train_label)
test  = PrepDataset(test_data, test_label)

In [ ]:
training_args = TrainingArguments(
    output_dir='./checkpoint',          # output directory
    num_train_epochs = 5,              # total number of training epochs
    per_device_train_batch_size = 16,  # batch size per device during training
    per_device_eval_batch_size  = 16,   # batch size for evaluation
    weight_decay = 0.0001,               # strength of weight decay
    logging_dir='./log',     
    do_eval=True,
    save_strategy='steps',
    evaluation_strategy = 'steps',
    fp16 = True,
    learning_rate = 2e-5,
    log_level='info',
    eval_steps = 100,
    load_best_model_at_end = True
)

In [ ]:
# def compute_metrics(self, pred):
#       labels = pred.label_ids
#       preds = pred.predictions.argmax(-1)
#       m1 = load_metric('accuracy')
#       # m2 = load_metric('f1')
#       acc = m1.compute(predictions = preds, references = labels)['accuracy']
#       # f1  = m2.compute(predictions = preds, references = labels)['f1']
#       return {'accuracy':acc}

In [ ]:
trainer = Trainer(
    model = model,
    args  = training_args,
    train_dataset   = train, # 학습 세트
    eval_dataset    = test, # 테스트 세트
    # compute_metrics = compute_metrics, # metric 계산 함수
    callbacks = [EarlyStoppingCallback(early_stopping_patience = 5)]
)

Using cuda_amp half precision backend

In [ ]:
trainer.train()

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:407: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
***** Running training *****
  Num examples = 4,570
  Num Epochs = 5
  Instantaneous batch size per device = 16
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 1
  Total optimization steps = 1,430
  Number of trainable parameters = 110,619,650

***** Running Evaluation *****
  Num examples = 1143
  Batch size = 16
***** Running Evaluation *****
  Num examples = 1143
  Batch size = 16
***** Running Evaluation *****
  Num examples = 1143
  Batch size = 16
***** Running Evaluation *****
  Num examples = 1143
  Batch size = 16
***** Running Evaluation *****
  Num examples = 1143
  Batch size = 16
Saving model checkpoint to ./checkpoint/checkpoint-500
Configuration saved in ./checkpoint/checkpoint-500/config.json
Model weights saved in ./checkpoint/checkpoint-500/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 1143
  Batch size = 16
***** Running Evaluation *****
  Num examples = 1143
  Batch size = 16
***** Running Evaluation *****
  Num examples = 1143
  Batch size = 16
***** Running Evaluation *****
  Num examples = 1143
  Batch size = 16
***** Running Evaluation *****
  Num examples = 1143
  Batch size = 16
Saving model checkpoint to ./checkpoint/checkpoint-1000
Configuration saved in ./checkpoint/checkpoint-1000/config.json
Model weights saved in ./checkpoint/checkpoint-1000/pytorch_model.bin
***** Running Evaluation *****
  Num examples = 1143
  Batch size = 16


Training completed. Do not forget to share your model on huggingface.co/models =)


Loading best model from ./checkpoint/checkpoint-500 (score: 0.3624347746372223).

TrainOutput(global_step=1100, training_loss=0.21573984319513495, metrics={'train_runtime': 227.3155, 'train_samples_per_second': 100.521, 'train_steps_per_second': 6.291, 'total_flos': 1427560419733680.0, 'train_loss': 0.21573984319513495, 'epoch': 3.85})

여기부터는 기존에 만든 모델에 적용해보는 부분

In [ ]:
text_classifier = TextClassificationPipeline(
    tokenizer = tokenizer, 
    model     = model,
    device    = 'cuda:0'
)

Xformers is not installed correctly. If you want to use memorry_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.

In [ ]:
text_classifier = TextClassificationPipeline(
    tokenizer = tokenizer, 
    model     = model, 
    device    = 'cuda:0',
    # top_k     = None
)

In [ ]:
# 새로운 데이터 생성

import os
import sys
import urllib.request
import json

ID = "E4_pVsh0x3azbPhb0zTR" 
KEY = "STUh3EX0rD"

def naver_api(where, what, how) : # where : 뉴스,article, blog, what : 우리가 찾을 검색어, how : 어떤 파일로 써줄지
    
    encText = urllib.parse.quote(what)

    for i in range(1,1001,100):
        url = "https://openapi.naver.com/v1/search/" + where + "?query=" + encText + '&display=100' + "&start=" + str(i)
 
        request = urllib.request.Request(url)
        request.add_header("X-Naver-Client-Id",ID)
        request.add_header("X-Naver-Client-Secret",KEY)
        response = urllib.request.urlopen(request)
        rescode = response.getcode()
        
        if(rescode==200):
            response_body = response.read()
            results = response_body.decode('utf-8')
            items = json.loads(results)['items']

            for item in items :
                f = open(how,'a',encoding = 'utf8')
                title = item['title']
                description = item['description']
                
                title = title.replace('<b>','')
                title = title.replace('</b>','')
                title = title.replace('&apos;','')
                title = title.replace('&quot;','')
                description = description.replace('<b>','')
                description = description.replace('</b>','')
                description = description.replace('&apos;','')
                description = description.replace('&quot;','')

                f.write(title + '\n')
                f.write(description +'\n')
                f.close()

In [ ]:
# 새로운 데이터 생성(장원영)
naver_api('news','장원영','장원영.txt')

In [ ]:
data1 = pd.read_csv('장원영.txt',sep='\t')

In [ ]:
# data안의 문장들을 리스트 입력
data_list = data1.iloc[:5000].values.tolist()
data_list

In [ ]:
# labe==1인 값을 리스트 안에 모음
label_1_sentences = []
for i in range(1, len(data_list)):
    result = text_classifier(data_list[i])
    if result[0]['label'] == 'LABEL_1':
        label_1_sentences.append(data_list[i])

# 결과 확인(LABEL==1인 문장들이 담겨 있는 리스트)
label_1_sentences

In [ ]:
# kkma 설치
# !pip install konlpy
# from konlpy.tag import 
# kkma = Kkma()

# def morph(input_data) : #형태소 분석
#     preprocessed = kkma.pos(input_data)
#     print(preprocessed)

In [ ]:
from konlpy.tag import Hannanum
from collections import Counter

hannanum = Hannanum()

words = []

for sentence in label_1_sentences:
    tagged_words = hannanum.pos(str(sentence))
    for word, tag in tagged_words:
        if tag.startswith('N'):
            words.append(word)

word_counts = Counter(words)

sorted_words = sorted(word_counts.items(), key=lambda x: x[1], reverse=True)

for word, count in sorted_words:
    print(word, count)

In [ ]:
# 2번째 데이터
naver_api('news','카리나','카리나.txt')
data1 = pd.read_csv('카리나.txt',sep='\t')
data_list = data1.iloc[:10000].values.tolist()
data_list
label_1_sentences = []
for i in range(1, len(data_list)):
    result = text_classifier(data_list[i])
    if result[0]['label'] == 'LABEL_1':
        label_1_sentences.append(data_list[i])

words = []

for sentence in label_1_sentences:
    tagged_words = hannanum.pos(str(sentence))
    for word, tag in tagged_words:
        if tag.startswith('N'):
            words.append(word)

word_counts = Counter(words)

sorted_words = sorted(word_counts.items(), key=lambda x: x[1], reverse=True)

for word, count in sorted_words:
    print(word, count)

/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py:1080: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
‘본스타미디어제작센터’ 2
정진솔 2
위키미키 2
정해림 2
“쇼파드 2
그랑프리 2
최초… 2
나이비스 2
체감하시 2
닭볶음탕 2
퐁당퐁담 2
음방을 2
오픈…JCL 2
허영지 2
됐다(정희 2
['영앙제 2
음방하다 2
음방하 2
리스펙트 2
“‘Spicy’ 2
속설 2
닫아”(정희 2
찐팬 2
극장 2
펜트하우스 2
킹받 2
“나이비스 2
수록”(정희 2
존경해 2
않았냐 2
목금토일 2
MBCFM4U 2
음방, 2
돼”(정희 2
신인 2
너스레 2
영앙제 2
에스파♥ 2
칼단발 2
=선미, 2
정호연, 2
고민시 2
무더위 2
=선미 2
복숭아 2
피치 2
로즈 2
‘Spicy’, 2
‘관심↑’ 2
맛 2
['바비인형 2
싱크로율 2
‘인간 2
바비인형’ 2
신축성 2
타이트 2
자카드 2
문양 2
영화제行 2
선다‥K팝 2
간다…K팝 2
['“극강 2
스캣”…말로·박라온·강윤미·김민희 2
['말로·박라온·강윤미·김민희 2
16일(현지시각) 2
휴양 2
도시 2
제75회 2
[사진=쇼파드] 2
53,570 2
53,570장 2
['앰버서더 2
고혹美 2
주최·주관사 2
마포구 2
매치’(GOOD 2
양성 2
본스타, 2
키즈전문제작사 2
잇츠 2
예고…라이브 2
['효연 2
김종민 2
하고파…母 2
최애=장원영 2
['다시, 2
셋째 2
엄정화 2
댄스가수 2
유랑단 2
전국 2
유리X효연 2
소시 2
멋있어 2
2순위 2
유리 2
어머님 2
태교 2
가요 2
['아이브→르세라핌→에스파→(여자)아이들, 2
전성시대 2
일주 2
블록체인 2
생태계…내 2
[김주완 2
프로젝트 2
톱(Girls 2
수(128만 2
모드하우스 2
['초인플레 2
인기몰이 2
‘아르헨티나판 2
트럼프’[원호연 2
1위(389,369장)…NCT 2
8,946장 2
1,591장 2
에스쿱스·정한·조슈아·준·호시·원우·우지·디에잇 2
형태 2
ⓒ투데이신문 2
80to23 2
김범성(광주화정초·6학년)군 2
15주년차 2
한국대표 2
엔터전문교육기관 2
전문학원 2
솔라 2
써클차트(구 2
가온차트 2
리테일 2
피처링, 2
데뷔까지···성큼 2
‘AI 2
기자회견 2
“그동안 2
처음”이라 2
“(나이비스가) 2
지지직거리거 2
뚝딱거릴 2
스무드하 2
섞여들어 2
컬래버레이션 2
시초 2
디바라 2
대단 2
씨 2
['카리나vs보아…이무진 2
“아우라 2
아냐” 2
(정희 2
협업 2
카리나vs보아 2
사진=SM엔터테인먼트 2
초동(발매 2
일주일 2
아이브·뉴진스·르세라핌·에스파 2
5단계 2
에스엠엔터테인먼트 2
“새 2
일냈다 2
세븐틴·르세라핌 2
TOP5 2
645,883장 2
['크롭티+체크치마 2
킬링 2
드림콘서트 2
트롯 2
영탁, 2
72,969회 2
1위…이찬원·박서진· 2
임영웅(44,414회 2
송가인(25,114회 2
안성훈(20,437회 2
황영웅(17,749회 2
지민(17,435회 2
카리나(16,723회 2
슈화 2
허실장’ 2
바꿨다…역대 2
1위→전체 2
1일차 2
137 2
5일차 2
156 2
매콤+달콤한 2
비주얼…팬들 2
‘심쿵’ 2
예쁘다”, 2
“윈터야 2
사랑해”, 2
“미쳤다” 2
재치 2
친언니와 2
Pixid’ 2
['\u200b(엑스포츠뉴스 2
터울 2
간호사 2
친언니랑 2
악수하자 2
허공 2
악수 2
될까 2
아이브·3위 2
김민지, 2
[김한준 2
85초 2
예선 2
통과 2
레인 2
FC국대패밀리 2
아이브, 2
극찬+감탄 2
(+ 2
‘Pixid’ 2
“남매 2
남매들 2
['르세라핌, 2
1위…에스파·원어스 2
말미 2
후보들 2
스테이지 2
['카리나-이민혁 2
MC→르세라핌, 2
점수 2
우위 2
NCT(엔시티) 2
1위…에스파·이무진 2
에스파→이무진 2
5세대 2
영광…르세라핌 2
기회 2
찾아뵙겠다 2
Spicy→Salty 2
단짠 2
자유분방 2
['이민혁-카리 2
르세라핌-세븐틴-아이브 2
경합(쇼 2
음악중 2
['비투비(BTOB) 2
경합 2
벌 2
808회 2
아이브…5월 2
맞대결 2
세븐틴(SEVENTEEN) 2
아이브(IVE) 2
르세라핌vs세븐틴vs아이브, 2
격돌 2
스타트 2
초극세사 2
플렉스 2
아니네…부모님께 2
스타킹 2
분홍 2
니삭스 2
['‘송일국子’ 2
삼둥이, 2
회상 2
뷰티줌 2
장원영·카리나 2
귀환 2
2000년대 2
주도 2
부활 2
연예계 2
도전하면서 2
“1년 2
딱붙옷 2
['송일국, 2
삼둥 2
근황…요즘 2
“작은데 2
움직여” 2
무장해제(슈돌 2
“12살 2
해제 2
“블랙핑크·에스파·(여자)아이들 2
직관하고파” 2
맛보 2
광팬 2
직관 2
같다” 2
바람 2
승채 2
아리아 2
그란데 2
둘째子 2
공개…새 2
보금자리 2
준범(똥별)이 2
낯가리지 2
카리나X윈터→하지원까 2
[슈돌 2
안방극장 2
육아월드 2
카리나-윈터를 2
하지원, 2
김준호子 2
요거트 2
분수 2
선봬 2
父子 2
플러팅 2
(슈돌)[전 2
봐…9년 2
똥별이(연준범) 2
자처 2
매콤 2
달콤한 2
입성기★ 2
제이쓴네, 2
['[스한:ⓔ위클리] 2
하이틴…한 2
['ⓒ이혜영 2
com\u200b 2
시동 2
보니…(슈돌 2
제이쓴, 2
['제이쓴 2
감동(슈돌 2
인테리어디자이너 2
['[어게인TV] 2
슈퍼맨이돌아왔다 2
슈퍼맨이돌아왔다에서 2
불가…슈돌 2
또래 2
하이틴같 2
자유분방한 2
끌려다니지 2
주체적 2
에스파(닝닝, 2
그랜드볼룸 2
[★밤TView] 2
혹독 2
['슈퍼맨이돌아왔다 2
이사떡 2
만남→똥별이 2
윈. 2
이사 2
커팅식 2
제거…제이쓴 2
감동 2
손톱 2
['카리나·윈터, 2
배려심(슈돌 2
경영권 2
분쟁 2
이석훈 2
브런치카페 2
육아일기 2
체험 2
“예전 2
시켰다”고 2
매쉬포테이토 2
같아(슈돌 2
슈퍼맨이 2
도전한 2
네일·액세서리 2
엉뚱한 2
영혼 2
탈출 2
매쉬포테이토( 2
배변 2
돌보기[슈돌 2
['카리나X윈터, 2
사태 2
포테이토 2
['홍현희♥제이쓴 2
분유 2
투척…매쉬포테이토 2
['ㅈ에스파 2
당황…남 2
당황 2
‘슈퍼맨이 2
유아 2
처음봐요 2
['은하철도999 2
솔티앤스위트 2
솔티 2
스위트(Salty 2
무기 2
능숙한 2
부탁해 2
‘SPICY’ 2
성행 2
예감 2
시크·도 2
아이라인 2
효 2
카리나·3위 2
신기록(137만 2
2929 2
컴백무대 2
이번주 2
다채로운 2
MC…설윤 2
대신해 2
흥분 2
나가고라 2
내놨다 2
기대감↑ 2
인스타, 2
손짓 2
본인들 2
['허영지, 2
가상세계 2
준비( 2
출연진 2
['카리나(Karina) 2
자매들 2
결단력 2
직관력 2
사이스 2
해(Saithe 2
지배하 2
화끈하네 2
10th 2
1위(52,736장)…에스 2
19,507장 2
6,817장 2
사쿠라·김채원·허윤진·카즈하·홍은채) 2
좋다→닝닝 2
있다…MZ다운 2
만족감 2
정형화 2
['영탁, 2
101,838회 2
1위…이찬원·임영웅·박서진·황영웅 2
TOP5[기 2
박서진(25,823회 2
황영웅(23,094회 2
지민(20,266회 2
카리나(18,655회 2
진(18,497회 2
안성훈(15,691회 2
송가인(12 2
2TV. 2
['“인스타그램 2
무서우면이라 2
속사포로 2
불만 2
표출 2
허영지는 2
(슈 2
“준범 2
”라 2
준범(똥별) 2
사진=KBS2 2
가득한 2
홍현희♥제이쓴 2
준범앓이…SPICY 2
심작 2
약해…카리나·윈터, 2
제이쓴♥홍현희子 2
빠졌다(슈돌 2
도전(슈돌 2
“누나들 2
약해” 2
(슈퍼맨 2
쥐뿔도 2
보셨나 2
덕질하거 2
지구오락실 2
너뮤 2
여잔데 2
여리여리한데 2
티파 2
이쁘네영 2
성당 2
예쁘네요… 2
김태희, 2
연느님, 2
욕심가득 2
카리나였습니 2
진땀흘리 2
세팅 2
데이타 2
피로 2
싹 2
비즈 2
맛집 2
23년 2
애기들 2
장난감 2
목걸이라 2
비싼건지; 2
무료방문상담 2
신청안내 2
ㅁㅊㄷ 2
사진뜬거 2
공유해야함요 2
이사진 2
안예쁜 2
예쁜건 2
포트레이트꺼던데 2
잘어울리네요 2
JBHAND작가작 2
미도색 2
헤드 2
칸리 2
['NGC3372 2
촬영일시 2
촬영장소 2
뉴질랜드 2
오클랜드 2
(보틀 2
보름달 2
대상중 2
조준 2
헤더먼트 2
눈코입 2
입구조 2
호감ㅋㅋㅋ너무 2
드레스_ 2
['정직한결혼준비- 2
결직웨딩❤️ 2
잘어울려서 2
뮤비에서는 2
보면볼수록 2
예뻐요;; 2
빠젓네욤 2
허헣ㅎ 2
좋습미 2
고3 2
입시때 2
쌤 2
흐헣 2
◆답변 2
질문글 2
금지◆ 2
에타카리나성운 2
['에타카리나성운 2
첫만남 2
서호주 2
칼바리 2
망원경 2
경통 2
art135mm 2
/익스텐더) 2
-가대(삼각대) 2
아스트로랩스T3au 2
가이드경 2
가이드 2
단독샷 2
우오오오오오 2
와ㅏㅏㅏ 2
드릉드릉 2
재조명이유 2
파울라페 2
작약 2
얼굴크 2
싱싱 2
상처 2
잘왔어요 2
형광빛 2
코랄요 2
봐주셔유) 2
실바핑크 2
만개 2
챌린지하는데 2
미연x카리 2
찰떡이네욛ㄷ 2
(뉴진스) 2
장원영(IVE) 2
카즈하(르세라핌) 2
설윤(엔믹스) 2
입성형 2
눈성형 2
돼어있어요 2
글라스 2
안구 2
미백 2
뽀송하 2
카리나예요♡♡ 2
카리나(여신) 2
웃는거예쁜, 2
손발 2
파란색 2
덩치 2
['베트남 2
사악 2
전소미 2
첨봄 2
이쁘네마네 2
글올라 2
관심도없엇는데 2
시기 2
넋놓고봣네 2
같애 2
['안유진 2
여리여리한지 2
['카리나더 2
닮진 2
뱀상미 2
깜짝놀랐어 2
차분 2
유니크하네요 2
빈티지한 2
존멋 2
['엘르 2
멋있잖아요… 2
미쳤는데요… 2
201호 2
지젤- 2
222호 2
얼굴라 2
카리나같은얼굴형 2
에뛰드헤어팡팡 2
자연갈색모 2
2호 2
브라운(연한갈색모) 2
3호 2
내추럴 2
블랙(새치,블랙모) 2
마무리~~ㅎㅎ 2
컬렉션&gt 2
컬렉션&gt; 2
웰컴투마이월드 2
티저들 2
대자연 2
삘받아서 2
ㅎㅎㅎㅎㅎ 2
기본틀 2
카리나님한테 2
실물발톱 2
닮은거같아 2
올려봅니당 2
카페내 2
떡밥 2
즐감 2
와꾸 2
기사사진 2
쌩얼~연한 2
전신샷 2
정면대결 2
넣을라다 2
육수들 2
발작할까봐 2
['[앱상품][푸마] 2
245 2
보여요(지송) 2
구본승 2
10기 2
옥 2
같아 2
최애한테 2
유니폼 2
♡카리나♡ 2
희귀 2
엘프같아서 2
['이짤 2
윈터한테 2
입덕했습니다 2
만두아닙니까 2
윈터네욯ㅎ 2
존예네욬ㅋ 2
건강미 2
남자팬 2
이제알았죠 2
그와중 2
커리 2
무엇ㄷㄷ 2
솔로곡 2
이쁨ㅋㅋㅋㅋ 2
한거봤는데 2
이번신곡 2
빠진거 2
넘부러움ㅋㅋㅋ다음생엔 2
리뉴얼 2
재입고 2
유칼립투스향 2
1637644250 2
베이비파우더향 2
1637645157 2
243.4 2
와피데 2
에보 2
4.1 2
['[앱상품]모다카리 2
140 2
['원피스-셀프 2
악세 2
잘어울림 2
이뻐이뻐 2
이쁘네염 2
아가야들 2
직업 2
훈녀도아닌 2
첫인상만봐서 2
이성적호감 2
중소 2
카리나급 2
성격은좋음 2
일치 2
슴미 2
['서호주 2
드래곤볼 2
비루스 2
초저녁 2
온사 2
지평선 2
롱패딩파카 2
롱패딩을 2
장난아니네요 2
열중쉬어 2
시전 2
['저녁~밤뿌 2
발향력 2
강제카공ㅋㅋㅋㅋ 2
['여배우들픽 2
누 2
ㄹㅋㄷㅍㅍ바 2
시향해볼때 2
소개받앗어욯ㅎ) 2
시향해 2
소분교환 2
첫향 2
약재달인물 2
카리나ㅠㅠ 2
서가대 2
미쳤어 2
아니냐구요 2
뽐뿌왔음 2
왜이렇 2
하관작고 2
조현 2
핫팩유닉 2
12p 2
핫팩통팝니 2
지난주 2
뉴짤 2
니스공항 2
['아코스튜디오스페이스 2
집업니트 2
앱 2
앱을 2
보풀 2
착용사진 2
소매부분 2
잡을거 2
부러워요ㅠㅠㅠ 2
카리나눈 2
쌍수 2
고민중입니다ㅠㅠㅠ 2
['마영전 2
라티야 2
신캐나왔길래 2
어떤분들 2
기믹 2
전역들 2
사냥꾼 2
점포 2
수박깨 2
놀이 2
패션룩 2
데님스커트 2
상하의룩 2
이름바 2
['프방트 2
득템 2
보러갔다왔네요 2
믈브TV 2
나오더라구용 2
인기영상 2
너무귀엽게 2
1티어 2
쇼케사진 2
인정해 2
코빡이들아 2
같은하늘아래 2
나이스 2
카키색바지 2
세미와이드 2
핏정 2
밴딩 2
카키카키하 2
카키 2
팬츠를 2
중독 2
에스파카리나조합 2
올여름까지 2
같은데요 2
피케 2
허리라인 2
루비 2
수지 2
근접 2
['수지vs카 2
극사세 2
왜인지 2
클래식한 2
딥티크 2
오르페옹 2
퍼퓸드말리 2
엑스니힐 2
스윗모르핀 2
프라팡 2
골필뱅 2
퍼시픽 2
락모스 2
베로니크 2
베르데지르 2
밀레에베르토 2
멘타이멘타 2
토탈리화이트 2
2ml: 2
에따리브르도랑주 2
레이어드룩이었어요~ 2
시크함 2
['오프숄더 2
미툤다 2
전문채널 2
오르페오 2
프롬스 2
바이올리니스트 2
지휘자 2
카넬라키스 2
심포니 2
['잼잼~(마트리카리 2
댄싱퀸)&amp;태안 2
농산물다참(글라올러스구근+백합구근 2
구매후기 2
['잼잼~마트리카리나~♡ 2
댄싱퀸장미 2
파랑 2
우연찮게 2
보고,마트리카리 2
화단 2
풍성 2
보고픈 2
프리저드색 2
그린색 2
마음속 2
했다가요 2
딸아이 2
첫템 2
령목 2
['[카리나IG] 2
['“다음 2
BS243. 2
새해맞이 2
3평 2
적정 2
미학 2
시전해 2
다이아몬드12. 2
6.5인치 2
한발 2
악마대공 2
전전 2
괴물화 2
접속하시 2
['큰거 2
가방속 2
소지품 2
무슨향 2
달콤 2
쌉쌀한 2
블랙베리 2
조말론 2
코롱 2
연우 2
이쁘긴하 2
['조녜 2
사황 2
듸진다 2
['허접카 2
@마조 2
@마조네 2
셀피 2
깔끔한 2
였는데요~~ 2
['졸라이쁘네요 2
엘르 2
개취로 2
한표… 2
브롯백이었는데요~ 2
만두 2
쉐입 2
캐주얼 2
대중적 2
아이들이에요^^ 2
베돌리페 2
주로하다보 2
구관아이들 2
리페인팅 2
관심이가네요^^ 2
요아 2
2021신상 2
아인데요 2
안구교체 2
기본리페만으로 2
무한이쁨이랍니다 2
멜빵바지 2
['최애 2
시험기간 2
보다보 2
품절입니 2
예쁘네 2
['ㅘ 2
파란렌즈끼 2
향사님 2
청순하다가 2
시크해지 2
감사하겠습니닿 2
+) 2
&amp 2
['통통튀 2
의외 2
주량 2
소개할게요~ 2
크로셰 2
제취저 2
오더아가 2
집에갔던 2
오너님 2
문자 2
의기소침 2
제게텐션 2
선물합니다~~♡ 2
['흐앤므 2
돌고래( 2
['리바이스 2
【실사】 2
엊그제 2
흐앤므 2
세일할 2
돌고래 2
맘에들어서 2
입어봐써요 2
살짝쿵 2
잘추 2
다잘하 2
엘프같기 2
연남이랑 2
한강같은데 2
데이트 2
너낌 2
미방 2
은혜로운 2
섭외 2
진짜이유 2
레이어드한 2
유니크하 2
서스펜더룩 2
['카리나몸매 2
왜케예뻐요 2
부럽 2
['이세계 2
삐슝빠슝 2
응애공주 2
엘프네요 2
리메이크곡 2
엘프 2
아님여 2
끼떠는거하 2
아이돌하려 2
태어난거같아 2
올려논건 2
머리장식 2
주머니 2
있는건 2
고글 2
앨락 2
밸라 2
-&gt; 2
['위즈위드 2
득템이요❤️ 2
그리기 2
['요정아니구 2
#인물화 2
#초상화 2
#연필드로잉 2
#인물드로잉 2
#색연필 2
#손그림 2
#수채화 2
미약한 2
누끼 2
다크모드 2
방지 2
외출시 2
나만볼 2
['카리나,카즈하 2
안되 2
골반퀸연예인gif 2
116세 2
종족 2
뱀파 2
장비 2
스태프 2
폼클렌징, 2
토너세트 2
1637645663 2
폼클렌징+토너 2
1637906529 2
품절이며, 2
카우스 2
연청바 2
디자인이 2
라츠유입니 2
메디힐 2
['드르릉 2
빠졌죵 2
번개탼 2
오~카리나(사회 2
박봉규 2
추억 2
실방 2
산들분들께 2
나의마음 2
다짐 2
생각하누 2
시작됬다 2
전적 2
비치운다 2
상대팀 2
참고 2
멋찌다 2
감탄사 2
헤어스타일^^ 2
['❤️❤️❤️ 2
수험생들 2
&lt;이미지 2
보라빛 2
염색한 2
['넘예쁘 2
아치모양이 2
일자눈썹 2
계랸형 2
카리나님얼굴 2
잘어울리는것같아요~ 2
아치형 2
반면 2
매력만점 2
곧있 2
대반란시대 2
웨이보 2
전략RPG 2
코스 2
중국에서 2
표정연기 2
대박인거 2
옷핏 2
찍은거 2
첨이 2
뭘입어 2
['안젤리아, 2
기지인형 2
안젤리아 2
다 2
햇다 2
도와달라 2
습격 2
중이엇고 2
오락가락 2
57.79 2
【상품사진】 2
【상품리뷰】 2
월욜 2
오왔쓰네요 2
['150사이즈 2
브라운색상 2
꽃무늬 2
캉캉 2
포코 2
['+ 2
☆ 2
드래곤이 2
우주 2
릿지윙 2
족족 2
교배 2
(네뷸라 2
있었어여) 2
&lt;누아르나인&gt 2
&lt;누아르나인&gt; 2
템 2
픽했는데요 2
아카이브볼드 2
제품들이 2
믿음 2
단군이래 2
탑티어인거 2
근대 2
전신 2
부자연 2
우쨋던 2
영상봅니당 2
여고생 2
진리 2
['스위스 2
디자인&amp;라이프스타 2
코프스레입니다 2
10일날 2
무법도시 2
퀄 2
마디 2
아무것 2
안입은 2
하얀구두 2
신겨봐야 2
못추는 2
['소2 2
소녀전선 2
소녀전선2에서 2
유추 2
찾아뵐게요~~ 2
다있는곳 2
원목트레이 2
트레이 2
이불매트리스 2
솜 2
빵빵하 2
넣었나봐요 2
설명절 2
가족들 2
행복한 2
워뇨 2
젊음 2
리더의자격 2
겸비 2
무적 2
['받는상대 2
(딸칵 2
#인스타그램 2
암소보관한 2
눈색 2
관절바디 2
양말 2
박스 2
장치 2
찾아보지두 2
않았네용 2
심 2
그런가용 2
이런심 2
활용하나용 2
스탈이라서 2
힐 2
봤어욜 2
하하핫 2
지젤이네요 2
스타리그 2
암튼 2
결론 2
존예입니 2
['코캎 2
이시대 2
최고GOAT 2
되시고^^ 2
불금 2
눈♥ 2
쌍커풀 2
['차린건쥐뿔도 2
에트몽 2
쉬는날 2
보는걸 2
귀여운거 2
이쬬 2
카리나)#TU16 2
ver1. 2
#TU16 2
대응패치 2
적용되는거 2
말씀 2
영상으로봣는데 2
저럴 2
아재 2
두근두근 2
카리나블라우스 2
19. 2
93*4 2
【주문날짜】 2
(시차) 2
【상품이미지】 2
【주문서이미지】 2
【주문리뷰】 2
다른분들 2
노랑 2
같은뎋ㅎ 2
귀엽잖어 2
뚱냥이 2
좋. 2
ㅓ 2
ㅈ. 2
든거 2
머야 2
끼애애ㅐㅇ앵애ㅐㅐ애애ㅐ 2
윈터&amp 2
['마참내 2
4291502 2
어흑 2
시절이 2
굿바 2
짱이뿌다 2
제복이지 2
['메이시스 2
네이비체크 2
켈빈 2
드로드 2
['연우 2
인기절정 2
유지비법 2
자체… 2
원영 2
사진보고 2
힐링하 2
몇백장잇어요… 2
너무좋아요 2
운동할때두 2
원영이랑 2
남돌 2
관심없어여ㅠㅠㅋㅋㅋㅋ 2
원영이 2
['이쁘네요 2
어떨 2
지휘관:으음 2
제2 2
빅뱅 2
카리나:으음 2
그럴려 2
무대의상이다보 2
빡세 2
이런것마저 2
팔색조 2
해원 2
특정 2
박소현 2
러브 2
영상보는데 2
찰떡이더라구요 2
힘든데요 2
카타리나…크 2
생명체 2
['120사이즈 2
민트색 2
나오는거 2
셋다 2
['청순함 2
기본스킨 2
청춘 2
자유로운 2
락스패너 2
불꽃놀이 2
검은고양 2
아가씨 2
난류연속 2
무장한 2
이성질체 2
변장 2
211018일 2
영상통화 2
였어요~ 2
가요대축제 2
출퇴근길 2
애착 2
찰떡쓰 2
연옌들 2
머 2
어린시절 2
교정기빼 2
대광 2
3합 2
사용한 2
280g 2
바늘사이즈 2
4.5mm 2
4mm 2
도안 2
기타정보 2
풀오버 2
불가하기 2
후루룩 2
다른아이돌들은 2
이쁜거알아 2
큰감흥은 2
실물보 2
생각듬 2
각자취향존중 2
개인적인기준 2
현폼 2
6중주 2
중순 2
비대 2
랜선 2
김원 2
&lt;플리즈프로젝트&gt 2
&lt;플리즈프로젝트&gt; 2
아빠안잔다 2
플리즈프로젝트 2
픽했는데요~ 2
이너템으로 2
화재인데요 2
제품정리 2
플러스 2
98년 2
한채 2
흑조, 2
뱀파이 2
&lt;창원피부관리 2
탄력관리 2
추천&gt; 2
방문전 2
['♀️ 2
['골때녀 2
집중탐구(Feat. 2
국대패밀리 2
홀란드 2
쌩얼 2
땀 2
심상치않 2
인간계아닌 2
한한 2
경악 2
(슈돌) 2
제이슨 2
'슈퍼맨 2
['디젤(Diesel) 2
안들어오 2
늑힘 2
당당 2
뽀인트 2
생머리 2
모습보고 2
깜놀 2
모자핏 2
예쁘자나 2
민규, 2
휴닝카 2
코디하 2
공항짤 2
삘와서 2
덕심 2
포스팅중^^^ 2
CP77 2
['녕뚜 2
카리나편,, 2
오ㅏ,, 2
유죄인간 2
샤넬 2
모티브 2
코디들 2
가득가득 2
이로스타 2
웨딩슈즈 2
스타일링하 2
발목스트랩 2
최고최고 2
스미니(SMini) 2
카리나만한 2
급격 2
꼴 2
금발버리 2
세젤예 2
카리나겨절 2
연관검색어가 2
대두 2
지는거 2
찜해뒀어 2
뚜렷 2
예쁜거아닌가요 2
코코다니입니다 2
찐사랑 2
['[차쥐뿔](23. 2
쾌녀 2
카리나_ 2
예능감 2
1순위, 2
+_+ 2
이영지와 2
케미 2
대박쓰 2
매수해 2
짤 2
2hot4u 2
올리비아 2
칼세 2
#김민정 2
#닝이줘 2
어디있어 2
착용하시 2
켄 2
후원사인 2
브랜든 2
초정 2
하이주얼리를 2
MLB데님팬츠 2
빡센 2
['카리나공항패션 2
프라다가방 2
왜이렇게 2
2.프라다 2
￦130,000 2
판매처 2
판매금액 2
#2023여자SS헤어트렌드 2
#송파미용실 2
#송파역미용실#가락동미용실 2
완판녀 2
샵사 2
퀄리티도 2
참석차 2
생화 2
퍼퓸으로 2
정국향수 2
카리나향수 2
무슨향일까 2
궁금하기도했는데 2
#정국 2
향수라 2
관심이가더 2
고급져~ 2
["흑발VS금발 2
풀어볼까합니다 2
해외일정차 2
한번접어 2
열아홉 2
비니 2
스타일링해 2
젤리비 2
(3ABNM0726-50BKS) 2
미드 2
바디수트 2
가방,키링,옷,목걸이,크롭탑 2
블랙&amp;레드 2
425USD 2
옆면 2
자수패치가 2
메신저 2
바이브 2
안찌 2
체질❌ 2
유산소운동 2
만보 2
걷기운동 2
오머 2
충격적 2
착시현상 2
프로 2
온라인커뮤니티 2
이젠 2
미쳐벌임… 2
◈ 2
광진하우스토리 2
똥별이(준범) 2
손거울 2
다음주 2
체구 2
기분탓 2
아닐거 2
정답 2
날씬 2
뱃살 2
라투숄 2
어뜩해ㅜㅠ 2
유짐 2
갯섬 2
웅장 2
효녀오브효녀 2
페페토입니다 2
큐트하 2
해먹 2
즁 2
페미닌 2
에이 2
페미닌한 2
버블감 2
*_&lt; 2
양일 2
['클루투 2
봄트렌드 2
구경해 2
시작할게요~ 2
❤ 2
#연예인패션 2
#걸그룹패션 2
와이드팬츠 2
니트벙거지 2
휴대 2
성별 2
뿔테안경으로 2
남녀공용 2
모델이구요 2
번호 2
797482-5801 2
2870 2
378 2
3000원 2
매장가격 2
높을꺼에요 2
18k로즈골드 2
찰나 2
카리나사복패션 2
일정차 2
볼께용 2
크롭후드 2
와이씨에이치 2
헤메코에서 2
직접적 2
소름 2
슬리브 2
65,000원 2
여리여리한 2
페이스 2
인스타그램&gt; 2
바이미나 2
바이미 2
에디토리얼비 2
갓곡 2
컴백한 2
심쿵사 2
무관심 2
70만원 2
707,000 2
슬림한핏 2
밑단 2
확대 2
흔적 2
멕이에요 2
공항패샌 2
코디했는데 2
볼캡모자 2
가방정보 2
멤버들❤️ 2
5기 2
[願い事ひとつだけ] 2
소원 2
페미닌스러운 2
체리코코 2
라빈 2
남쪽구슬 2
발견하긴 2
봄코 2
초여우 2
맨투맨만 2
애매 2
딱~ 2
['품절된 2
마감 2
2차 2
['빠빠 2
카리나원피스&amp;슈트&amp 2
맘 2
['카리나원피스 2
아동원피스 2
3-4 2
4-5 2
5-6 2
6-7세 2
베이비슈트 2
18개월 2
아동 2
♡ 2
카리나op. 2
봄바람 2
살랑살랑~ 2
벚꽃 2
꽃놀이 2
봄점퍼 2
산뜻 2
[あなたを愛してくこと] 2
3기 2
謎 2
수수께끼 2
차도녀 2
표본 2
['청순한 2
평상시 2
모음zip 2
(송혜교, 2
고윤정, 2
송혜교, 2
응원봉 2
스봉 2
#에스파멤버 2
카리나(한)2000 2
유구 2
전통 2
컨셉으로 2
어떨까요 2
[チャンス] 2
[챈스] 2
6기 2
[氷の上に立つように] 2
크롭맨투맨세트 2
풀착장 2
트레이닝 2
이쁘구 2
잘맞고 2
무난한 2
코디하셔 2
와이드팬츠, 2
데님팬츠, 2
레깅스까 2
찰떡콩떡 2
친숙 2
[最短距離で−Take 2
– 2
테이크 2
어웨이 2
모습인데요 2
게 2
후리스인데요 2
은목걸이, 2
은목걸 2
은목걸이입니다~ 2
초커 2
은목걸이 2
13년 2
뷰티선배 2
봄자켓 2
표면감 2
‘사운드 2
아이템중 2
['런웨이 2
와이드데님, 2
걸그룹, 2
계단 2
40분 2
알았어욯ㅎㅎ 2
['nt_source=cloudreview&amp;nt_medium=exp&amp;nt_detail=20230420 2
지치해요 2
한국비건인증원 2
절차 2
쿠기스 2
천연유래 2
전성분 2
원대 2
오픈숄더 2
투피스 2
58,000 2
보부상가방 2
나온다길래 2
시청 2
셋업들이예요 2
면 2
코마사 2
끈 2
입체자수 2
와펜로고 2
러닝(달리기), 2
레저 2
세리 2
플레이리스트 2
│태연 2
블러셔하 2
12시 2
크롭탑, 2
["이영지 2
어패럴 2
아트홀맥입니 2
재즈보컬 2
4인 2
보컬리스트 2
야구잠바 2
키높이운동화 2
카리나코디 2
화보보고 2
핫한지 2
찍어버리셔죠 2
셀럽들중 2
["차쥐뿔 2
영지님 2
['샵사이다 2
홍보 2
유트브 2
카리나편, 2
스윗 2
예쁜걸 2
키스 2
튼튼 2
낮기온 2
슬릭컷스탈일입니다:) 2
끝리 2
슬릭한 2
세워드리자ㅜㅠ 2
새빛둥둥섬이라 2
드리자ㅠㅠ 2
갓기예요 2
블랙스완,,,그잡채 2
영애님 2
애기씨 2
선녀 2
블루씨 2
(˘̩̩̩ε˘̩ƪ) 2
가쓰 2
카리나에게서 2
착용한 2
만원 2
어느순간부터 2
유영진 2
성 2
음색 2
윈터까지 2
제로웨이스트에 2
적합한 2
생분해되 2
사이버네틱 2
혼란 2
전시 2
옷,하투 2
['케플러 2
코디제안 2
함께좋 2
핫플 2
두시 2
발레 2
['할명수 2
에스파카리나&amp;지젤 2
와중 2
미디움 2
골든구스 2
한강에서 2
베어버전 2
118유로대 2
애장템 2
보러가실게요 2
시카토너 2
마구마구 2
프렌들리 2
추구 2
브랜드답 2
비윤리적 2
동물성 2
배제 2
블랙카고원피스 2
부츠 2
카리나공항패션 2
구매링크 2
후ㅜㅜ 2
5cm. 2
소개해볼게요 2
블렌딩 2
구키스치약 2
어른들 2
편견 2
담 2
['리페한 2
청순가련형 2
한복 2
캠핑장 2
할로윈 2
['❤️에스파(aespa) 2
&lt;Spicy(스파이시)&gt; 2
움짤❤️ 2
금발하니까 2
카리나모 2
야구모자 2
필요할듯요 2
봄꽃놀 2
되네요^^ 2
카리나님은 2
어디거 2
홍보겸 2
은발 2
여튼 2
구매할시 2
준다고해요 2
팜플렛과함께 2
칸16억 2
['열일하 2
하이주얼리 2
마이하트주얼리 2
마이해피하트목걸이 2
200만원 2
큰사이즈 2
400-500만원 2
쇼피드 2
공홈은 2
로코블랑 2
컨설턴트 2
버블리우 2
스엠 2
항 2
우카 2
받고왔어 2
평 2
21시 2
17시 2
공휴일 2
휴무 2
말하기 2
쎄비 2
진-짜 2
사각프레 2
안산 2
베니스안경입니 2
#볼타 2
#볼타01 2
문의 2
고풍 2
정반대 2
밍고에요 2
오 2
남방 2
['카페카리나(karina) 2
백제고분 2
46길 2
서암빌딩 2
1층 2
4번출구 2
도보 2
4분 2
명함 2
송리단길쪽 2
위치한 2
카페카 2
낮 2
커피 2
린넨울 2
소매 2
165cm 2
77사이즈 2
여자친구 2
수제비누 2
샴푸바 2
웰니스 2
호평 2
다운 2
바닐라슈 2
겐조 2
카리나찡 2
구수한 2
형돈이 2
야구모 2
볼캡추천 2
해외콘 2
퓨어민트치약 2
21살 2
2주년 2
20230519 2
2탄 2
떨스티 2
여성들 2
해외일정 2
트렌디하 2
비밀 2
홈마 2
직찍 2
웨딩 2
쥐 2
컴플렉스 2
카리나❤️ 2
300만원 2
차린건쥐뿔도없지 2
콜라보 2
피드입니 2
8종 2
이웃님 2
럭키OPPA 2
특집 2
ㅋ) 2
판단 2
자타공인 2
1번 2
여성점퍼 2
구경 2
여니하니님 2
겁 2
미디엄 2
전용기 2
귀멸 2
칼날 2
한정판 2
한정 2
00년생 2
대상 2
정리 2
이기광 2
가요광장 2
보여드릴게요 2
저장(O) 2
강경 2
['&lt;금발 2
왜케 2
급상승 2
끗 2
['루즈핏 2
린넨100 2
선염 2
린넨100% 2
고급린넨이 2
정체 2
카즈하, 2
팬아트 2
주차장 2
지붕위 2
207회 2
회차정보 2
공식영상 2
힘 2
알려드려볼게요 2
케이스 2
튜브 2
타 2
22. 2
09 2
40대 2
다리 2
잠옷 2
몬세라트 2
긴소매 2
여성청자켓 2
데님셋업 2
인스타그램(@aespa_official) 2
착용샷 2
극 2
네크라인 2
필인더블랭크 2
이종석 2
하루종일 2
우치나 2
멕 2
톡톡 2
#미모 2
최소 2
2번 2
낭낭한 2
흑발변신 2
윈터부터 2
나연, 2
X몰빌딩 2
Y2K패션코디- 2
['에스파(aespa)(카리나, 2
애니멀 2
알레르망스핑크스 2
아이보리 2
헤메 2
데뷔초 2
홍대미용실 2
슬릭펌 2
쿨블랙염색 2
톤다운 2
실루엣 2
일명 2
400m 2
230513 2
플라잉요 2
요소 2
재밌고 2
모먼트 2
오피셜 2
그랜드 2
['옷잘입는연예 2
걸 2
베이스 2
갈래 2
홀터 2
체형 2
2022. 2
스톤 2
두피 2
착장정보 2
피부톤 2
유지해 2
딱 2
큐빅 2
꙼̈ 2
블루블랙 2
금호덴탈제약 2
3P 2
연령층 2
가을룩 2
맨투맨, 2
15 2
뿅 2
하얀색 2
3세대 2
베이비핑크 2
밑 2
['웬디 2
각 2
제안 2
필승조 2
['오오코 2
내돈내산 2
1,000ppm 2
용 2
주얼리브랜드 2
오드 2
사운드 2
2021 2
핫해 2
검정 2
당신 2
조차 2
여성옷 2
모스카토 2
다스티 2
하미유 2
백금발헤어, 2
여성비 2
방한모 2
행 2
노이르데지르 2
으째입니 2
카리나머리 2
여자패딩 2
산책룩 2
넷다 2
함유 2
하드 2
털 2
['포맨트 2
보미 2
캔버스 2
언제 2
출근룩 2
팝업스토 2
['태국 2
야시장 2
5만원 2
카리나]1월1 2
강타 2
['근데 2
23)_교복 2
키 2
☺️ 2
공식인스타 2
칼카리나 2
이곳 2
['창원피부관리 2
데뷔때 2
여성반팔티 2
스트랩샌들 2
별내미용실 2
예원쌤 2
레이어드컷 2
이러 2
사진모음 2
[술트리트파이터](2022) 2
끝 2
주변 2
은하철 2
999 2
하구 2
셋 2
보러가 2
02. 2
고수 2
할게요 2
그라데이션 2
필요 2
#닥터카리 2
크리스탈 2
실제 2
소비 2
#카리나사복 2
긴팔 2
알고리즘 2
금발한 2
블론드컬러 2
파워 2
30대 2
너드미 2
전격 2
★ 2
여자남방코디 2
파리티멘토 2
실버링 2
AS98 2
뮬(블로퍼) 2
희연사 2
프사하 2
일반적 2
프리뷰 2
원영, 2
짱 2
안그래 2
['예카리 2
힙합 2
카리나T 2
['비건젤 2
종이 2
이분 2
겉옷 2
0411 2
윈터(김민정) 2
[인스타콘서트](2021. 2
뭔지 2
수준 2
자극짤 2
트레이닝복 2
시그니처뷰티 2
여자청자켓 2
패키지 2
불구 2
마이크 2
따봉, 2
2월 2
약속 2
['컬렉션 2
아몬즈 2
선오픈 2
22SUMMER 2
스텝분 2
ㅠㅠㅠㅠㅠ 2
프레즐 2
스틱 2
한국인 2
카리나(Karina) 2
초대형 2
염색하 2
입냄새 2
사용가능 2
['애린에스테틱 2
작은얼굴 2
금발로보 2
하이틴배우 2
였어요 2
플리츠 2
3D 2
치약추천 2
#제이더블유페 2
['겨울쿨톤 2
#스파이시 2
출연(feat. 2
본방사수 2
공중파 2
수지구청점 2
다빈입니다 2
괄사 2
테라피 2
퍼지 2
턴업 2
쇼핑 2
긴팔티 2
친환경 2
수분 2
김연아 2
캣우먼 2
보라색 2
손가방 2
나일론 2
에스프레소바 2
이탈리안 2
세번 2
#디젤 2
은 2
['안나카리 2
아지 2
최강자 2
230601 2
['헤더먼트 2
여자연예인 2
데뷔티저, 2
사업 2
쇼퍼백입니 2
요시타카 2
유리코 2
연애 2
)라 2
재밌게 2
미니어처 2
시그니처 2
젠더리스 2
투샷 2
아이디헤어 2
가현쌤 2
230331 2
매거진파리 2
에스카 2
05 2
ㅜ 2
털어놔 2
['★ 2
양치 2
#에스파패션 2
유다정 2
아트박스 2
마이 2
올리브영러브젤 2
카리나(Anna 2
스튜디오춤 2
카리나•지젤 2
타입서비스(TYPE 2
8P 2
모달 2
데뷔싱글 2
더블라 2
먼저, 2
풀뱅, 2
소프트뱅 2
오디토리움 2
코랄색감 2
팁 2
천 2
썬글라스 2
▼ 2
파트별가사 2
&lt;네컷라이브&gt; 2
오버롤 2
230531 2
2P 2
['창원성산구 2
눈바디테라피 2
무선 2
이어폰 2
눈썹 2
별 2
불소함유 2
우리앞 2
타나카 2
열애 2
엠넷, 2
(⊃ 2
#칸카리 2
['ⓘ 2
│[이쁨주의] 2
["ⓘ 2
#에스엠 2
#SM 2
[이쁨주의] 2
잇템 2
크로스백 2
근본 2
더쿠 2
909 2
뮤뱅 2
#아로마오 2
#마사지오 2
#아로마테라피 2
케이팝제너레이션 2
화보패션 2
콜 2
레드브라운염색 2
자라원피스 2
조이 2
“ 2
미모…몸매까지 2
['숄더백 2
니 2
ㅇ 2
다나카 2
윈터,시크한 2
성실 1
정보성 1
ⓒ 1
카리나_공연 1
진지 1
성호경 1
초록색 1
추가적 1
가을겨울 1
75 1
네크라 1
래글런 1
롱길이 1
도톰한 1
구독 1
#카리나스파이시 1
콩이네리본 1
소개드릴 1
콩 1
새틴소재 1
빅리본자동핀 1
#반묶음핀 1
#빅리본핀 1
#여성헤어핀 1
#올림머리핀 1
것들 1
플라스틱 1
프리 1
동물성원료 1
실리콘 1
합성계면활성제 1
첨가 1
선언 1
닝닝(NINGNING)이, 1
5인조 1
가수LE 1
SSERAFIM(루세라핌) 1
홍은채(HONG 1
버라이어티 1
「EUNCHAE's 1
Diary」 1
신발색 1
출현 1
조회 1
60 1
시원섭섭( 1
['뮤뱅출근길 1
빨간체크오프숄더 1
카리나패션 1
빨간색 1
체크무늬 1
보세 1
군데 1
레시피 1
펜싱스타 1
순한바디워시 1
리뷰글 1
인증 1
랍니 1
500ml라 1
스몰로 1
생산 1
['오오코(OOCO) 1
B01E_RI 1
[24K. 1
닝닝님 1
메이크업카 1
해볼거에요 1
펑키 1
크으으~~ 1
흑발만 1
_Girls 1
Top_sm공식인스타 1
열일하 1
좋아하시져 1
헤헷 1
좋아합니닷 1
ㅋ. 1
['｢바닐라슈-한시 1
10｣최고 1
착용감 1
#가보시 1
['[국내수제&amp;홑겹] 1
가보시 1
뮬슬리퍼(10cm) 1
자체제작 1
이번기회 1
장만 1
절대절대 1
후회 1
아차깜박 1
하나놓침 1
발등부분 1
홑겹원단 1
['옷잘입 1
옷잘입 1
자취뿔 1
1대1 1
술한잔씩 1
존예보스 1
카리나이즈먼들 1
이겠냐만은,, 1
소매양털 1
너모 1
안찾아볼수 1
없었당 1
쇼트 1
화기애애한 1
['여자주얼리브랜드 1
OOCO,손담비 1
['손담비 1
보실께욤 1
손담비 1
이온 1
도금 1
24살 1
1학년 1
2학년 1
(※ 1
앰블럼 1
표시 1
잭 1
드미츄리 1
대준 1
대준이 1
롯데백화점 1
에비뉴엘 1
월드타워점 1
보테가 1
펌프스 1
뉴욕양기스 1
모델이 1
없더라구요❤️ 1
해볼꺼에요 1
스파이시활동 1
갓퀸카 1
겨절은 1
#비건치약 1
#치약추천 1
#미백치약추천 1
#온가족치약 1
#불소치약 1
#불소치약추천 1
#민트치약 1
20살 1
19살 1
순삭~ 1
결식아동 1
지원 1
키트 1
['[세종안경] 1
17WF 1
다비치안경 1
궁금하시 1
바탕화 1
aespa－karina－lifes－too－short－4k－wallpaper－uhdpaper. 1
/ 1
#MD 1
무대고화질 1
가격대 1
녹화방송 1
하이틴드라마 1
교복핏 1
['샵사이다(cider) 1
8만원치 1
샵사이다에서 1
핫한듯하다 1
캡쳐되 1
배송 1
예약배송 1
가능하다(같은 1
리폼해서 1
로우웨시트 1
일정→미국 1
바꾼거 1
플래티넘 1
숄더탑, 1
차쥐뿔(차린건 1
보실까용 1
&lt;블랙스완&gt; 1
베 1
카리나만 1
3월달 1
['먹방 1
이웃집 1
통통 1
약과쿠키 1
관심| 1
보영언니랑 1
식단 1
재고 1
「차린건 1
뿔 1
없지만(준비 1
없지만)」 1
【사진】aespa 1
카리나(2000년생) 1
발전하는구나( 1
문특보 1
핑크블러드 1
과사까지 1
슬리퍼 1
컨버스 1
인천공항을 1
운동화인데요~ 1
여자핸드백 1
이쁘져 1
텐아시아 1
'냉미녀' 1
인생네컷X1theK 1
진짜같다(꿀팁 1
속윈터 1
곰돌이키링 1
짱구반지 1
‘차린건쥐뿔도없지만’ 1
❤️✨ 1
청량한 1
어울리는거같아요 1
#차쥐뿔 1
['#차쥐뿔카리나가방 1
#짱구블루투스스피커 1
['하이틴룩 1
예쁘고ㅠㅠ 1
['Y2K 1
티셔츠보고 1
보이쉬 1
예쁘시드라구요 1
트위스트 1
10,500원 1
목걸이_헤이 1
섭섭하쥬 1
럭기oppa 1
저기가 1
기빨릴 1
차.쥐 1
하나만 1
헤어나올걸 1
관절 1
특기 1
동경 1
태연효영, 1
윈터로 1
대결 1
성황리 1
230520 1
['카리나에스테틱, 1
물광관리 1
등관리 1
여드름관리 1
#대방동피부샵추천 1
#대방동피부관리 1
카리나카리 1
뾰루지 1
['여자패딩 1
셀럽착용 1
업데이트된 1
유튜브에서는 1
다음날 1
티저를 1
8인조 1
걸그룹으로서, 1
list=PLCY3m9HlbuKVhmfV1MXx-KzLFlB0Mes9a 1
업그레이드 1
해달라 1
진상부 1
염소털 1
식모 1
바시티자켓입니 1
모습들 1
트러커 1
보스턴 1
삭스 1
일산만화학원 1
애니포스 1
어떨까 1
불소함유량 1
빨강색 1
고불소를 1
레드벨벳+에스파 1
캐럴 1
송 1
예리(99년생) 1
에리카 1
'밀리터리룩' 1
['에스파카리나, 1
여름반팔티 1
오오티디 1
히트 1
단아하고예쁘다 1
윤아와 1
참석했겠죵 1
단아 1
닝닝까지 1
뽀글이 1
잭캠 1
조사 1
엠넷 1
64 1
비중 1
ㄷㄷㄷ 1
레터프롬문, 1
작 1
블라우스구요 1
없을정 1
블랙스모키 1
미쳤다 1
보여드려용 1
테트리스 1
하이틴이라 1
흑발파 1
카리나&gt; 1
구두 1
굉장히눈 1
얼굴작으신건 1
원탑이실듯 1
그렇다보니 1
늘씬늘씬한 1
촉감 1
은은 1
펄감 1
억소리나 1
UPROXX(유프록스)라 1
웹사이트 1
['#아는형님#아는형님카리나댄스#아는형님카리나#아는형님에스파#카리나묵직#카리나과사#카리나과거사진#에스파카리나#카리나사진#카리나사진모음# 1
00. 1
22살 1
수원 1
형 1
168cm. 1
카리스마민호 1
베댓 1
업 1
hello82&gt; 1
춤동작 1
#제피란서스 1
#카리나다 1
분홍색 1
눈도장 1
씨방 1
#제피란서스카리니다 1
화분 1
꽃이진후 1
['&lt; 1
별개 1
로켓 1
펀처 1
마동석 1
강력 1
펀치 1
쇼츠 1
클럿스튜디 1
신이에요 1
매칭해줘 1
시너지 1
초포바로위 1
지난번 1
페이즐리 1
╰(*°▽°*)╯ 1
소화하기 1
어깨라 1
팔뚝 1
뱃살, 1
등살 1
이쁘잖아효,, 1
만화 1
08. 1
김포공항패션 1
손민수템 1
김포공항입국한 1
바이커 1
1615787 1
스포티한 1
디자인인데요 1
무리 1
롱슬리브 1
풋볼져지, 1
레이싱셔츠 1
블록코어룩 1
블록코어셔츠 1
롱슬리브입니 1
인스타에서 1
박한 1
미모열일하 1
단발병 1
230514 1
1991년 1
(미국) 1
더워잉 1
휴식 1
기간 1
슬로우 1
모션 1
파자마 1
오르시떼 1
A062 1
상하 1
세트인데용 1
오르시떼에서 1
남성복 1
나왔습니당 1
가을 1
계절 1
['패션블로거 1
마르잔 1
인스타그램, 1
파급력 1
데일리하 1
루머 1
미용 1
시술 1
응뎡임다잇~~ 1
써볼게요~ 1
롱린넨원피스 1
반품 1
62cm 1
114cm 1
스모크 1
짜여진 1
하츠 1
사랑스러워♥ 1
알레산드라 1
리치 1
['미국 1
너무x10000 1
서핑하다 1
['롯데에비뉴엘 1
저요 1
럭키 1
기다리신분들 1
운 1
1440*3200 1
['카리나10 1
10MB 1
최적화 1
사진아래 1
터치후 1
가지구 1
떄문 1
ㅎㅎㅋㅋㅋ 1
핑크가디건 1
['♡ 1
토파즈보정 1
@앵브록스 1
#ENGBROX 1
#앵브록스 1
#여름주얼리 1
#귀걸 1
코디모음 1
*레이첼콕스 1
#레이첼콕스 1
귀엽더라구요♡ 1
데님, 1
['포텐터진 1
#역대급 1
#뉴진스 1
#민지 1
⬇️⬇️ 1
포텐터진 1
이미지클릭 1
전쟁중 1
20일(토) 1
["#카리 1
“살찌 1
적도”…몸매 1
#백금발탈색 1
#백금발염색 1
#금발연예 1
‘sound 1
2023’ 1
공연차 1
태리쌤입니다 1
올블랙패션 1
다른느낌이라 1
흑발생머리로 1
없다 1
손석구까 1
손석구까지 1
코코다니입니 1
내추럴하면서도 1
무대(MBC 1
농구복 1
농구 1
동아리 1
바비인형' 1
위치:경남 1
창원시 1
가양로124번길 1
203호 1
필링 1
정 1
보리뷰 1
정.보리뷰 1
아정보 1
현아님 1

In [ ]:
# 3번째 데이터
naver_api('news','김채원','김채원.txt')
data1 = pd.read_csv('김채원.txt',sep='\t')
data_list = data1.iloc[:10000].values.tolist()
data_list
label_1_sentences = []
for i in range(1, len(data_list)):
    result = text_classifier(data_list[i])
    if result[0]['label'] == 'LABEL_1':
        label_1_sentences.append(data_list[i])

words = []

for sentence in label_1_sentences:
    tagged_words = hannanum.pos(str(sentence))
    for word, tag in tagged_words:
        if tag.startswith('N'):
            words.append(word)

word_counts = Counter(words)

sorted_words = sorted(word_counts.items(), key=lambda x: x[1], reverse=True)

for word, count in sorted_words:
    print(word, count)

/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py:1080: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(

르세라핌 500
김채원 489
사쿠라 437
김채원, 403
카즈하, 398
허윤진, 385
홍은채) 330
['르세라핌, 250
정규 203
1집 194
['르세라핌 190
1위 175
그룹 169
르세라핌(김채원, 167
서울 167
오전 161
주간 140
파트리샤 136
5월 132
방송 129
참석 129
톱 123
미연 118
앨범 117
뮤직뱅크 114
리정, 112
진행 110
최예나, 109
르세라핌(LE 105
홍은채 105
걸그룹 102
혜 100
오리콘 98
이 97
여자 97
신곡 95
등 94
아이들 91
차트 90
공개 86
일본 84
발매 82
허윤진 81
멤버 80
음악 80
이날 77
여의 77
['르세라핌(김채원, 76
판매량 76
블랙핑크 75
포토 75
혜미리예채파 73
리허설 69
영상 68
글로벌 67
예능 67
빌보드 64
활동 63
멤버들 62
랭킹 61
19일 59
영등포구 58
‘UNFORGIVEN’ 57
무대 57
진입 55
음반 54
스포티파 52
발표 52
유튜브 51
출연 51
가수 51
연속 51
스포티파이 51
2023. 51
별관 51
카즈하 50
마지막 50
차트(5월 50
한터차트 50
12일 50
첫 49
최대 49
최신 49
팝 49
세계 48
수 48
‘UNFORGIVEN 47
포즈 47
정상 47
하이브 46
스트리밍 46
05. 46
후속곡 45
지수 45
미국 45
퍼포먼스 45
2023 45
여의도동 45
채널 44
업체 44
‘주간 43
Rodgers)’ 42
['혜미리예채파 42
오후 41
이번 41
출근길 41
1일 40
르세라핌, 40
집계 40
28일 39
판매 39
15일 39
신관 39
공개홀 39
프시케 38
뮤직비디오 38
소속사 38
국 38
13일 38
장 37
지역 37
사이트 37
6위 36
만 36
일정 36
日 36
데뷔 35
시작 35
게재 35
['르세라핌(LE 35
퀘스트 35
김포국제공항 35
12 34
장군엔터테인먼트 34
수염 33
미모 33
타이틀곡 33
차 33
혜리 32
공식 32
조준원 32
기자 32
출국 32
2일 31
나 31
시즌2 31
200 31
매체 31
1년 31
['[사진]르세라핌 31
기록 30
리 30
자 30
2TV 30
더쇼 30
세븐틴 29
소속 29
말 29
등장 29
전문 29
데 29
비롯 29
도쿄 29
에스파 28
음악방송 28
뉴진스 28
언포기븐 27
19 27
정성호 27
곡 26
인기 26
쏘스뮤직 26
['걸그룹 26
레이블즈 26
4월 26
9 26
10개 26
언포기븐(UNFORGIVEN) 25
4주 25
속 25
송 25
방송인 25
컴백 25
이야기 25
2위 25
14일 25
송’ 24
美 24
개 24
것 24
리정 24
‘혜미리예채파’ 24
['‘혜미리예채파’ 24
예고 24
손가락 24
박슬기, 24
황수경, 24
박광선, 24
양준혁 24
사랑 23
김채원은 23
끝 23
멜론 23
폭소 23
최예나 23
여의주 23
고정우 23
스포츠 23
김요한, 23
최준석, 23
이장군 23
김태술, 23
김상욱 23
좌식 23
사우나 23
['김채원 22
리테 22
달성 22
브랜드평판 22
생방송 22
박소라, 22
트로트가수 22
10회 22
흥행 21
안유진, 21
이영지 21
인기가요 21
채 21
도전 21
에피소드 21
‘뮤직뱅크’ 21
8일 21
전 20
쥐뿔 20
3일 20
브레이크뉴스 20
박동제 20
기자= 20
플레이어’ 20
수록곡 20
중 20
들 20
세대 20
최고 20
획득 20
제 20
0시 20
스타 20
김의영 20
‘이브, 19
송’(집계기간 19
게스트 19
시간 19
마무리 19
3주 19
여정 19
팬미팅 19
수상 19
강서구 19
일 19
일간 19
아내’ 18
홍은채, 18
아이브 18
이브, 18
자리 18
인사 18
5도2촌 18
반응 18
술래 18
방송국 18
보 18
4일 18
로저스 18
카 17
‘인기가요’ 17
앨범차트 17
혜리부터 17
문제 17
챌린지 17
공연 17
5 17
결성 17
당 17
순서 17
예정 17
2 17
국제선 17
13 17
프리즘타워 17
조회수 16
레이블 16
거 16
부문 16
메시지 16
소감 16
번 16
여부 16
10 16
밀리언셀러 16
3위 16
해 16
신관홀 16
김의영, 16
방화동 16
하네다 16
마포구 16
이틀 16
102 16
음원 15
이후 15
질문 15
이태경 15
사진 15
주 15
포인트 15
12회 15
채원이 15
디지털 15
요리 15
역대 15
케이콘 15
초동 15
그 14
아내 14
글 14
김채원사진=르세라핌 14
해당 14
순위 14
7일 14
출신 14
해외 14
자신 14
비주얼 14
7시 14
써클차트 14
20일 14
아티스트 14
박수예 14
인터뷰 14
돌파 13
올해 13
근황 13
송(집계기간 13
하나 13
배우 13
‘빌보드 13
200’ 13
브랜드 13
동영상 13
제작진 13
우리 13
가운데 13
한국 13
50분 13
측은 13
이름 13
아이돌 13
21일 13
18일 13
팀 13
[포토엔HD 13
국내 13
자체 13
기사 13
‘언포기븐(UNFORGIVEN)’ 13
경호원 13
재팬 13
14 13
첫날 13
“‘K팝 12
모습 12
하루 12
신선한 12
나위 12
매력 12
유종 12
4세대 12
관심 12
폭격 12
저녁 12
2주 12
방탄소년단 12
역사 12
로제, 12
세일럼 12
일리스(Salem 12
맛집 12
연주 12
스페셜 12
도착 12
바이올린 12
입성 12
최단기간 12
14일(현지시간) 12
지난주 12
랭킹(5월 12
템페스트 12
14개 12
약 12
초이스 12
['르세라핌(김채원·사쿠라·허윤진·카즈하·홍은채) 11
‘UNFORGIVEN’, 11
차트인 11
장기 11
후 11
5일 11
지난달 11
지 11
['사진=쏘스뮤직 11
1 11
5위 11
['[라코이] 11
화제 11
완벽 11
미 11
최초 11
개최 11
혜미리예채파에서 11
방영 11
KBS2 11
웃수저 11
장군엔터 11
참여지수 11
미디어지수 11
소통지수 11
커뮤니티지수 11
8시 11
아이즈원 11
차트(집계기간 11
6일 11
동안 11
언니 10
라 10
2023년 10
성공적 10
['김채원, 10
프로그램 10
구성 10
레드벨벳 10
의 10
때 10
생각 10
진심 10
케미 10
몬스타엑스 10
참여 10
종영 10
라이브 10
성공 10
주관 10
채자 10
기준 10
25일 10
적극적 10
“르세라핌(김채원, 10
막내 10
등장한 10
포토타임 10
하트 10
제목 10
브랜드평판지수 10
분석 10
실시간 10
무한 10
정신 10
혼미 10
배신 10
3관왕 10
합산 10
5개 10
2관왕 10
9회 10
4위 9
사쿠라·김채원·허윤진·카즈하·홍은채) 9
다양 9
대상 9
산골 9
내 9
르세라핌(사쿠라, 9
['걸스데 9
사람 9
한편 9
홍은채)이 9
(혜미리예채파 9
초 9
신기록 9
바 9
24일 9
안무 9
909 9
역대급 9
예채파 9
흥미진진 9
태연 9
11일 9
추 9
스타인웨 9
무엇 9
좀비 9
게임 9
현장공개 9
상암동 9
고급 9
먹방 9
손절( 9
2일(현지시간) 9
레코딩 9
아카데미 9
6월 8
차쥐뿔 8
장기하, 8
13개 8
궤도 8
코너 8
30일 8
정착 8
조합 8
전소연 8
3 8
웃음 8
주헌 8
기 8
['맏언니 8
다섯 8
['혜미리예채파, 8
준비 8
오늘 8
춘천 8
#김채원 8
엠카 8
대 8
여성 8
UNFORGIVEN(언포기븐) 8
사쿠라,김채원,허윤진,카즈하,홍은채) 8
외모 8
칭찬 8
일부 8
102만4034장 8
편 8
타임 8
4 8
현대약품 8
['미스트롯2 8
전속계약 8
신 8
성적 8
16일 8
7 8
서사 8
9일 8
대표이사 8
8 8
손절 8
사칙연산 8
윷놀이 8
‘그래미닷컴’ 8
홈페이지 8
4034장 8
도겸 7
역주행 7
사진=르세라핌 7
자연 7
생활 7
28 7
안락 7
살림살이 7
게시글 7
21위 7
언급 7
일문일답 7
강다니엘, 7
드림캐쳐 7
유현, 7
더보이즈 7
케빈&amp;제이콥&amp;에릭, 7
원어스 7
환웅&amp;이도, 7
미래소년 7
고정 7
의상 7
쇼 7
1. 7
쌈아치 7
행복 7
콘셉트 7
엠카운트다운 7
#르세라핌 7
#사쿠라 7
#허윤진 7
#카즈하 7
#홍은채 7
누적 7
감동 7
물결 7
스테이지 7
11회 7
쎈 7
녹화 7
5. 7
10CM, 7
['[TD포토+] 7
은행장 7
바이올리니스트 7
화음 7
피아니스트 7
콩쿠르 7
최연소 7
독 7
슈베르트 7
언포기븐, 7
678,748 7
815,056 7
1,171,643 7
1,436,984 7
4,102,431 7
피프티피프티 7
‘톱 7
100’ 7
10주 7
완성 7
음방 7
도전기 7
강타 7
2023(KCON 7
앙코르 7
9천 7
레스토랑 7
지적 7
리정) 7
예채파(최예 7
인원 7
국가·지역 7
완탕 7
협업 7
고공행진 6
10시 6
30분 6
콘텐츠 6
10위 6
조슈아 6
고군분투 6
예 6
인터넷반응 6
혜미리예채파(혜리·미연·리정·최예나·김채원) 6
댓글 6
뉴스 6
출연자 6
화제성 6
23위 6
인스타그램 6
치열 6
감사 6
대표 6
관전 6
부담 6
‘언포기븐(UNFORGIVEN) 6
행사 6
음원+음반 6
예능감 6
뭐 6
싱가포르 6
27일 6
7위 6
변신 6
돌입 6
#LESSERAFIM 6
#SAKURA 6
#CHAEWON 6
#YUNJIN 6
#KAZUHA 6
점령 6
['이영지, 6
위 6
휴대폰 6
케이스 6
직후 6
듯 6
노래 6
특별 6
촬영 6
‘Good 6
윈터, 6
피어나 6
['라우브(Lauv) 6
민니 6
가창 6
멜로망스 6
그랜드슬램 6
미소 6
시크한 6
BAE173, 6
촬영차 6
키오스크 6
100 6
아트엠콘서트 6
프로코피에프 6
소나타 6
(FEARNOT)’라 6
천 6
한솥밥 6
아이돌그룹 6
드라마 6
르세라핌은 6
“이번 6
['제이오원, 6
엑스 6
마지막날 6
제로베이스원 6
엔하이픈, 6
아이콘 6
케플러 6
싸이커스, 6
앤팀 6
하인드 6
['오늘(10일) 6
일주일(집계기간 6
윷 6
무효 6
18주차 6
오늘(8일) 6
신경전 6
10개국 6
마라탕 6
사흘 6
7,586장 6
‘그래미 6
어워드’ 6
은채 5
26일 5
폭발 5
5인조 5
언니들 5
복작복작 5
입소문 5
1529 5
“난 5
착용 5
아이 5
댄스 5
22위 5
24위 5
세상 5
의지 5
화 5
질주 5
화이트 5
마린룩 5
명 5
성장세 5
눈물 5
확정 5
‘엠카운트다운’ 5
29 5
현지 5
‘원톱’ 5
28일(일) 5
존재감 5
원톱 5
맏언니 5
집 5
게스트들 5
소 5
30위 5
입장 5
트와이스 5
호응 5
연결 5
우아한 5
현장 5
‘언포기븐’ 5
소녀시대 5
두 5
기회 5
유주 5
릴리 5
가수(여자)아이들, 5
ICHILLIN(아이칠린) 5
패션 5
인형 5
한 5
오늘(18일) 5
지원 5
오늘(16일) 5
톱10 5
등극 5
고유 5
6관왕 5
야망 5
그랜드 5
슬램 5
오디션 5
설거지배 5
없지만’ 5
장기하 5
77위 5
출국장 5
평가 5
달라라네트워크 5
7,383 5
보디가드 5
깜찍 5
예고편 5
흥미 5
10일 5
주간차트 5
쇼케이스 5
125 5
['오늘(9일) 5
성향 5
(최예 5
그래미닷컴 5
전국 4
건 4
둘 4
이영지, 4
화사 4
결혼 4
['‘K-팝 4
톱송 4
스타일 4
지난해 4
서양화 4
아침 4
댄서 4
이동 4
선택 4
계속 4
되길 4
신뢰 4
사진=ENA 4
힙한 4
['종영 4
막 4
“걸그룹 4
스케줄 4
최단 4
위아래 4
줄 4
플레이 4
자리매김 4
캐시 4
단발병 4
‘이브 4
처절 4
9위 4
합류 4
Rodgers)’은 4
엔싸 4
투표자수 4
블리처스, 4
최강자 4
자랑 4
▲ 4
포스터 4
행진 4
고난 4
그동안 4
극찬 4
['이영지 4
최다 4
이슈 4
22일 4
정석 4
결심 4
현악 4
3중주 4
스테이크 4
상황극 4
채원 4
21 4
익숙 4
키즈 4
로제 4
초대 4
러블리한 4
단발 4
홀 4
치명적 4
이채연 4
밖 4
크롭 4
저희 4
제154회 4
압도적 4
성장 4
['‘미스트롯2 4
['김의영, 4
['‘미스트롯2’ 4
뒤 4
최상위권 4
석권 4
시점 4
극 4
6위…K-팝 4
‘UNFORGIVEN(feat. 4
마쿠하리 4
멧세 4
동명 4
519,520 4
1,257,137 4
720,384 4
1,830,887 4
눈빛 4
차린건 4
뒷이야기 4
트로피 4
주인공 4
‘차린 4
쫄깃한 4
긴장감 4
고혹적 4
[SE★포토 4
개념 4
메이킹 4
프로젝트 4
지망생들 4
보이그룹 4
김채원-사쿠라, 4
르세라핌(김채원 4
영광 4
점 4
제공 4
선 4
타인 4
앵콜 4
‘더쇼’ 4
SSERAFIM(르세라핌), 4
(이펙스), 4
기욱(ONEWE), 4
GHOST9, 4
앨리스(ALICE) 4
8,011장 4
“음악 4
혜미리(혜리 4
대결 4
구도 4
규칙 4
고조 4
할래라 4
캐시가 4
2일차 4
102만장 4
소식좌 3
박재범 3
1천 3
순항 3
173위 3
자리하 3
조금조금 3
양 3
개항장 3
갤러리 3
벨라 3
인천 3
채령 3
종료 3
3rd 3
힌트 3
시골 3
타깃 3
성과 3
케미스트리 3
입증 3
호흡 3
걱정 3
블핑 3
제품 3
다수 3
데이식스 3
성진, 3
마크 3
BAE173 3
이한결 3
25위 3
육각형 3
인재 3
사회 3
훌륭 3
멤버들이 3
특급 3
[똑똑SNS 3
공유 3
“퇴근 3
재밌고 3
기대 3
장악 3
엔터뉴스팀 3
성료 3
29일 3
밥친구 3
‘K-팝 3
종영소감 3
예능프로그램 3
총결산 3
3종 3
미션 3
몸 3
상징 3
종 3
채널A 3
예능돌 3
캐릭터 3
혜미리예채파, 3
가능성 3
['‘혜미리예채파’, 3
연령대 3
케이팝 3
표 3
대방출 3
김채원사진 3
#EUNCHAE 3
#뮤직뱅크 3
#MusicBank 3
#출근길 3
女 3
20주차 3
전시 3
” 3
팬심 3
뮤비 3
빌보드200 3
슈가 3
작가 3
얼굴 3
당시 3
지향 3
진짜 3
발언 3
선미, 3
조명 3
고생 3
루 3
비통 3
락 3
짱구 3
맹구 3
콧물 3
뮤지션 3
콜라보 3
없지만 3
입 3
궁금증 3
증폭 3
유쾌 3
조합별 3
퀴즈 3
리테일앨범주간차트 3
이상 3
['리정, 3
마무리…후속곡 3
타이틀 3
다시보 3
윤택 3
이벤트 3
캐시를 3
1위…2위 3
태연·3위 3
소개 3
레터 3
Parts’ 3
‘예채파’ 3
눈길 3
접수 3
101위 3
표정 3
허리 3
출범 3
리더 3
‘All 3
Nothing’부터 3
Parts’, 3
‘위대한 3
쇼맨’ 3
‘This 3
Me’, 3
스테이씨가 3
세련 3
©최은희 3
oso0@slist. 3
러블리 3
피스 3
빠져드 3
상큼 3
브 3
위대한 3
쇼맨 3
16일(현지시간) 3
멤버들(김채원, 3
#EUNCHAE. 3
메 3
옆 3
블랙 3
에이디 3
오도이촌 3
막바지 3
저 3
LOCK(락) 3
최강자’ 3
제외 3
11개 3
전지적 3
참견 3
엄마 3
‘케이콘 3
2023’(KCON 3
4,327,928 3
격 3
끝판왕 3
치아 3
안유진(아이브), 3
김채원(르세라핌), 3
아이스크림 3
도겸, 3
미공개 3
출연분 3
[★포토 3
감탄 3
자세 3
하반기 3
운영사인 3
경호 3
활발 3
['[포토]르세라핌 3
컨셉 3
1주년 3
“르세라핌 3
종합 3
['뉴진스 3
국내외 3
써클차트(구 3
가온차트 3
리스너 3
뉴진스, 3
만큼 3
9일(현지시간) 3
장원영 3
2관왕…글로벌 3
플레이어 3
르세라핌만 3
길 3
마음 3
뿔 3
이펙스, 3
크랙시 3
한음 3
‘THE 3
SHOW(더쇼)’ 3
09 3
초동(발매 3
일주일 3
벨벳 3
Y2K 3
10초 3
안 3
히트곡 3
119 3
퀄리티 3
['혜미리(혜리 3
야외 3
취침 3
청신호 3
고민 3
한잔 3
05 3
직행 3
110 3
0 3
8회 3
4,034장 3
당일 3
만국 3
공통어 3
창작물 3
그래미 3
어워드 3
부산 2
애 2
임시개장 2
밤 2
1,000 2
“컵라 2
‘은채 2
스타일기’ 2
구독자 2
비비 2
뷰 2
장기흥행 2
답 2
토크 2
“ 2
중구 2
거리 2
둘이 2
안착 2
카톡 2
식사 2
157개 2
183개 2
114개 2
재회 2
시청자 2
혜미리예채파(이혜리, 2
걸스데 2
이혜리 2
경험 2
바탕 2
동생들 2
급식실 2
과정 2
코로나19 2
학생 2
65위 2
차지 2
유명 2
대비 2
목표 2
여자아이 2
김채원·사쿠라 2
솔로 2
시각 2
서정욱, 2
0.4 2
시청률 2
굳건 2
청년 2
시청자들 2
즐거워”라 2
“더할 2
['카드(KARD), 2
이별 2
카드 2
‘ICKY’ 2
‘K팝 2
“바쁜 2
힐링 2
성 2
종영, 2
MZ예능…시즌2 2
이브 2
엔딩 2
적극 2
동생 2
환상 2
중앙대 2
활용 2
전방위 2
폭발적 2
이태경PD 2
육아 2
금쪽 2
조사 2
무궁무진한 2
활약 2
흑 2
사상 2
근데 2
힐링할 2
경기 2
오늘(28일) 2
막방 2
리정→혜리, 2
소식 2
리듬 2
카즈타 2
1위…몬트 2
◆ 2
몬트 2
플랫폼 2
심장 2
대박 2
리사 2
['리정 2
“나 2
싶다”라 2
빛 2
미주 2
케이블채널 2
토요일 2
연출 2
성적·퍼포먼스·브랜딩 2
주제 2
만날거야 2
인생 2
마을 2
없지만(차쥐뿔), 2
다음 2
카리나 2
강렬한 2
46위 2
공개…고난 2
게재했다”고 2
증명 2
오늘(24일) 2
꿈 2
작 2
자유로운 2
논란 2
채령, 2
형원, 2
비난 2
술 2
회 2
진 2
급증 2
불후 2
28위 2
29위 2
관련 2
호시, 2
김향기, 2
채영, 2
크리스토퍼 2
네이티브 2
전환 2
시선 2
여섯 2
‘트위스트 2
XL’ 2
백 2
김채원(22) 2
이영지는 2
자랑해 2
비교적 2
잠수교 2
프리폴 2
컬렉션 2
크리스토퍼→스트레 2
60분 2
최근 2
“혹시 2
눈치 2
카즈하에 2
사죄 2
최고난 2
윈터 2
단체 2
라면 2
도재정· 2
콜라 2
본업 2
모드 2
카리스마 2
정규앨범 2
마무리…역대급 2
女 2
만화 2
선물 2
응원 2
굿 2
파츠(Good 2
분석결과 2
['‘K-909’ 2
순 2
20 2
['사쿠라·김채원·허윤진·카즈하·홍은채) 2
호성적 2
연기 2
“unforgiven” 2
잘록 2
국가 2
강원특별자치도 2
강원도 2
계기 2
방문 2
포토+] 2
태양 2
매치 2
김채원-홍은채 2
핌둥이들 2
펀치 2
발랄 2
심쿵 2
볼하트 2
김현우 2
(콘텐트비즈니스본부 2
르세라핌→스트레 2
스테이씨 2
1위…르세라핌 2
월드 2
쌈무 2
허윤진(왼쪽부터) 2
포브스 2
정준하 2
폼 2
21일(일) 2
승리 2
꽃 2
예쁜애 2
귀요미 2
머리 2
원어스(ONEUS), 2
단발머리 2
방송일정 2
레전드 2
['[포토]김채원, 2
남심 2
현장포토 2
스커트 2
멋 2
꽃받침 2
세 2
['박승철 2
위그스투디오, 2
장소 2
협찬 2
지점장 2
항암환자들 2
요구 2
디자인과 2
박승철 2
위그만 2
항암 2
니즈 2
정확 2
충족 2
항암가발특화점 2
비결 2
개발 2
수제 2
인모 2
가발 2
갑작 2
소화 2
기념 2
미디어 2
초청 2
라이스할레홀 2
피아노 2
선사 2
추가 2
17일 2
위엄 2
김가람 2
강하연 2
겹경사 2
생일날 2
전속계약…정성호 2
둥지 2
[톱스타뉴스 2
현재 2
TOP100 2
1위…UNFORGIVEN 2
출발 2
신기록→멜론 2
1위… 2
상승세 2
여자아이들 2
우산 2
비 2
우리들 2
지칭 2
6위…데뷔 2
역사상 2
기간 2
美빌보드 2
새역사 2
네티즌 2
4,725(20%)표 2
뮤뱅 2
14일(일) 2
챔피언 2
전파 2
지옥 2
실수 2
다국적 2
프로듀스 2
26위 2
귀국 2
입국장 2
입국 2
‘케이콘’ 2
1주 2
카즈하-김채원 2
예쁨’[포토엔HD 2
손하트 2
손 2
카우걸 2
(차쥐뿔 2
너 2
1위…에스파·이무진·원어스 2
담당 2
미인 2
임플란트 2
4관왕 2
손인사 2
없지만에서 2
필요 2
송. 2
고혹 2
르세라핌(허윤진, 2
그간 2
했다” 2
편견 2
조슈아&amp;도겸, 2
10월 2
발매한 2
[TV캡처 2
엑스디너 2
‘팬픽(FAN 2
PICK)’ 2
컴백쇼 2
팬픽(FAN 2
랭킹+韓 2
심취 2
네 2
비투비, 2
['트윙플 2
팬픽 2
['오늘(12일) 2
9만7383 2
보호 2
랭킹+한국 2
과즙미 2
허윤진) 2
시부문대상 2
시 2
홍은혜,수질환경부문대상 2
사단법인 2
한국다문화예술원 2
부원장 2
국민브랜드상 2
㈜우리 2
정성순대 2
전형태 2
건설부문최우수상 2
㈜옥산건설 2
회장 2
의미 2
뮤직 2
소성진 2
방시혁 2
님 2
팬클럽 2
흑발 2
핫한 2
스타들 2
프로그램명 2
준비한 2
재계약 2
든든 2
티키타카 2
플렉스 2
노력 2
11 2
1천만명 2
월별 2
맛 2
에너지 2
동행 2
주체성 2
빌런 2
Champion)’ 2
쇼챔피언 2
랩 2
차트(5월15 2
손가락질 2
상관 2
['빌런 2
장식 2
기욱, 2
드리핀, 2
고스트나 2
앨리스, 2
머스트비 2
아찔 2
눈 2
악마 2
1일차 2
오프라인 2
125만장 2
2연속 2
2배 2
르세라핌(김채원·사쿠라·허윤진·카즈하·홍은채) 2
8만9000장 2
스타일링 2
이사배 2
핑크색 2
트레이닝복 2
온라인 2
‘틀린그림찾기’ 2
민규, 2
박형식 2
노윤서, 2
임시완 2
박지후 2
이솜, 2
전여빈, 2
김서형, 2
장미희, 2
고아성 2
천우희, 2
김윤아, 2
고현정, 2
이성경 2
한효주, 2
정려원, 2
광진구 2
운동 2
트레이닝 2
포함 2
7,798장 2
사회자 2
인기가수 2
정우선, 2
한석영 2
밸리댄스 2
아랑 2
고고장구팀 2
음반차트 2
“이래서 2
“그냥 2
할래”라 2
발현 2
와중 2
“제 2
저렴한 2
먹었다”라 2
털어놨다 2
애국가 2
실패 2
리정X최예나X김채원, 2
김채원에 2
고백 2
유력 2
나코·히토미 2
강혜원, 2
김민주, 2
나코, 2
히토미, 2
조유리, 2
7586장 2
110만장 2
판매고 2
정상+스포티파 2
‘일간 2
0. 2
팔았다…역대 2
(캐시) 2
거야 2
측면 2
핵심 2
너머 2
전설적 2
1020세대 2
하루만 2
밀리언셀러…역대 2
여름…해수욕장·계곡 1
나들이객 1
북 1
해운대구 1
물 1
재밌 1
해운대 1
송정해수욕장 1
주말 1
해변 1
피서철 1
역주행·‘이프푸’ 1
불씨 1
터졌다…MV 1
천만뷰 1
한개 1
먹어” 1
인정(스타일기 1
인정 1
서로 1
첫인상 1
“채원 1
없지만… 1
300 1
시즌2로 1
조슈아, 1
2002년 1
생 1
22세 1
2019년 1
역주행…후속곡 1
반전 1
볼륨 1
몸매 1
윙크…팬심 1
대지진 1
['‘차트 1
역주행’ 1
‘MV 1
뷰’ 1
1000 1
고공행진…MV 1
1천만뷰 1
1000만건 1
화장 1
고우림♥김연아 1
[TV스포 1
173위…4주 1
연속진입 1
['‘장기 1
흥행’ 1
['은채랑 1
장인 1
실제 1
배 1
그룹(사쿠라·카즈하·홍은채·김채원·허윤진) 1
한국에서 1
1월 1
브랜평판 1
유해강 1
에디터 1
사쿠라X은채 1
맞다” 1
(‘스타일기 1
스타분 1
거냐”라 1
스타일”이라 1
“언니 1
않냐”고 1
인천시 1
신포로23번길 1
66 1
이곳 1
사 1
한국미술협회 1
회원 1
감자칩 1
통 1
더하네…컵라 1
공감 1
인기몰이… 1
역주행…스포티파 1
13,489장 1
4,433장 1
엔하이픈(ENHYPEN 1
희승,제이,제이크,성훈,선우,정원,니키) 1
♥류준열 1
“하루 1
때도”(혜미리예채파 1
각자 1
카톡수 1
장르 1
장악…요즘 1
‘女봐라’ 1
리얼리티 1
15∼29세(영 1
1위(한국 1
리서치 1
시즌1 1
마니아 1
시즌2도 1
영 1
피플 1
보석 1
가치 1
이혜 1
['이혜리부터 1
인도 1
이것 1
['김채원(18)양 1
통제 1
칸막이 1
학교 1
방역 1
학력평가 1
교내 1
응시 1
희망한 1
확진 1
K-애정템] 1
‘와이케이’ 1
예리 1
셀럽들 1
와이케이 1
전년 1
성장률 1
매출 1
100억원 1
진출 1
['나인투식스 1
31일 1
1위(10,096장)…Various 1
2,015장 1
미연·민니·소연·우기·슈화) 1
1,913장 1
['[K체인저스]⑩K콘텐츠 1
생태계 1
조성 1
['‘아이브’ 1
장원영·안유진, 1
‘르세라핌’ 1
대표적 1
‘4세대 1
아이돌’ 1
선두주자들이 1
입지 1
청하·강다니엘·이채연·권은비·조유리·최예 1
상위권 1
['미국 1
31일(현지 1
차트(6월 1
1주차 1
스타서베 1
7개 1
설문투표 1
281명(팀) 1
대상…가수·배우· 1
수호 1
36명 1
후보 1
[6월1주차]케이팝 1
투표 1
['엔하이픈 1
1위(27,630장)…보 1
5,737장 1
AB6IX(에이비식스 1
전웅·김동현·박우진·이대휘) 1
5-1 1
김채원(포항제철초 1
4-3 1
김채은(풍천풍서초 1
5-3 1
김해민(황성초 1
6-1 1
김효주(포은초 1
5-7 1
남송민(양포초 1
3-6 1
김채원(유강초 1
2-1 1
김채은(도봉초 1
3-5 1
김태윤(황성초 1
2-3 1
김하늘(장곡초 1
1-1 1
김한별(구미봉곡초 1
1-2 1
['김정혜, 1
김한섭, 1
류기백, 1
민재기, 1
박보성, 1
박봉희, 1
박성숙, 1
박신유, 1
박옥자, 1
박장우, 1
박태안, 1
박효영, 1
변준철, 1
신미 1
신민주 1
신수영 1
신승묵 1
신지영, 1
신홍섭, 1
양유진, 1
윤기주 1
윤선연 1
팬텀싱어4…2위 1
14위 1
489개 1
1,511개 1
280,000회 1
99건 1
45개 1
가구시청률 1
2049 1
시청 1
가구수 1
76 1
임영웅…이효리·엄정화·화사· 1
고딩엄빠 1
박미선(122점), 1
최예나(120점), 1
신봉선(117점), 1
김채원(115점), 1
채널A. 1
인재…멤버들 1
['혜리에 1
굳건해져…이태경 1
6인 1
상황 1
['△ 1
투데이신문 1
청년플러스 1
서포터즈 1
1기 1
소통⑭ 1
차원 1
판단 1
“더 1
후회도‥시즌2서 1
만났으면”[일문 1
퇴근 1
“시즌2서 1
만나길…오래 1
걸리더라도” 1
시즌2, 1
제작진·출연자들 1
있어 1
“방송 1
못보여줘 1
아쉬워” 1
책임감 1
강해…큰 1
됐. 1
만나길 1
혜리=육각형 1
인재…처절한 1
마무리…무대 1
김선우 1
아쉬워…모든 1
뜨거웠다…이끼 1
1500만뷰 1
엠넷·KBS 1
2TV·MBC 1
성료…生라이브 1
자부심 1
혼성그룹 1
[사진제공=각 1
방송화 1
캡처 1
역동적 1
군무+완벽 1
시간” 1
['“누적 1
10억뷰” 1
메이커…정규 1
멤버들” 1
최단기록 1
메이커 1
공중파 1
종료…K팝 1
종영→김채원 1
“좋 1
친구들 1
행복” 1
‘음악 1
경기’, 1
‘99초 1
컷’ 1
“미연→김채원, 1
발산 1
동료들 1
찾아뵙도록 1
하겠다”고 1
유발자 1
초대가수 1
서울캠퍼스 1
총학생회 1
학생처 1
학생지원팀 1
축제 1
슬로건 1
’청진낭만‘ 1
청룡 1
’. 1
대체불 1
“완벽한 1
멤버들…더 1
기대” 1
정규1집 1
성료…K-팝 1
['류승범, 1
통합 1
비드라마 1
시리즈 1
부문1위…미미·세븐 1
88 1
혜미리예채파(혜리·미연·리정·최예나·김채원, 1
59 1
새끼(신애라·정형돈·장영란·홍현희·오은영·박재연, 1
58 1
新가능성 1
부제 1
애정 1
종영…혜리→미연 1
‘EXID’ 1
‘위아래’ 1
ALL콤보 1
“개 1
교체→ITZY 1
…시즌2 1
섭섭 1
“힐링 1
됐다” 1
있었 1
“저에 1
힐링타 1
혜미리예채파가 1
99초 1
컷 1
즐거워” 1
모먼트+힙한 1
일상 1
오나…김채원 1
있어[Ce:스포 1
종영…벌써 1
“그런데 1
않을까”라 1
‘채’자 1
“다른 1
종영…‘눈물바다’ 1
가나…김채원 1
활활 1
작별 1
“누 1
울어” 1
축 1
‘여성’ 1
‘여행’ 1
['혜리·미연·리정·최예나·김채원·파트리샤 1
한국리서치 1
계획 1
눈물…왜 1
눈물바다 1
음원차트 1
아치울 1
호원숙 1
지음 1
나라찬·방탄소년단 1
디 1
19명 1
0표 1
카즈타(434명), 1
나라찬(410명) 1
…김채원, 1
말했과, 1
부정 1
중…글로벌 1
26 1
뛰네…팬심 1
뛰네 1
진입…후속곡 1
역주 1
장기흥행…후속곡 1
5천 1
할게요 1
역할 1
2촌 1
리정X김채원, 1
‘혜미리예채파’에서 1
“내 1
”이라 1
채원나 1
히트 1
카운트다운 1
['리정X김채원 1
제니할게요 1
이민가지 1
데이 1
핌둥이들~(뮤직뱅크 1
출근길)[뉴스엔TV 1
['드림캐쳐, 1
제니할게요…리정X김채원, 1
['‘엠카’ 1
홀릭 1
선보였다”고 1
댄스챌린지 1
유행예감 1
['레전드 1
신예 1
대결…김태호·나영석, 1
[엑s 1
김태호PD 1
사단 1
제작 1
이력 1
차별점 1
‘여성 1
전성시대’ 1
거두기 1
릴레이…언어 1
장벽 1
‘걸그룹 1
시장 1
각인 1
29,837점 1
점유율 1
6위…대중적 1
써클차트(5월 1
13곡 1
5장 1
즐거움 1
색 1
醉(취)하다 1
ⓒ 1
사물 1
풍경 1
화폭 1
미술 1
醉 1
13시 1
나라찬·디케이지 1
25명 1
카즈타(184명), 1
미국·일본서 1
릴레이 1
성적→브랜딩 1
회… 1
“다시 1
우린” 1
관련해 1
혜리→최예나, 1
만날거 1
['“편의점이란 1
일반적 1
94년생 1
되 1
['이혜리 1
3월 1
산 1
남녀 1
프로들 1
대결…SG골프 1
시즌4 1
매주 1
일·월 1
이미지 1
안녕하세 1
비트 1
['[셀럽이슈] 1
외모칭찬 1
논란…소신발언 1
대응 1
안유진 1
카리나에 1
자유 1
옹호 1
찾아온다…후속곡 1
공개…강렬비트+완벽한 1
칼군무 1
안무+힙한 1
감성 1
['‘SG골프 1
시즌4’ 1
일요일·월요 1
['이브, 1
아내…르세라핌, 1
역량 1
고난도 1
23일(현지시간) 1
23일 1
1위(24,544장)…엔하이픈· 1
2,384장 1
유나이트(YOUNITE 1
은호·스티브·현승·은상·형석·우노·DEY·경문·시온) 1
철쭉 1
45.5 1
33cm, 1
9번 1
취(醉)하다 1
30일(화) 1
서구 1
가정동 1
화실 1
운영 1
등지 1
국제교류전 1
랭크 1
['23일(현지 1
김채원) 1
시즌 1
동양 1
갑론을박 1
환대 1
상대방 1
식 1
['[왓IS] 1
“카리 1
예쁘다” 1
뿐인데…이영지, 1
‘소 1
발 1
초대해 1
취중 1
진담 1
조회 1
수(1912만 1
['거뜬한 1
음반판매량 1
홍은채)도 1
명곡(신동엽·김준현 1
416개 1
2,480개 1
639,000회 1
133건 1
52개 1
신상출시 1
편스토랑(이유리 1
박나래…전현무·유재석·백종원 1
김채원(92점), 1
27위 1
옥탑방 1
문제아들 1
김숙(90점), 1
환장 1
박나래(86점), 1
아빠들 1
장윤정(84점), 1
박원숙 1
받자…“제 1
바” 1
불편함 1
‘차쥐뿔’ 1
03월 1
트롯맨(황영웅·민 1
4,325개 1
4,762개 1
109,000회 1
2,603건 1
115개 1
명곡(신동엽 1
04월 1
보이즈 1
플래닛…2위 1
1,570개 1
5,072개 1
543,000회 1
299건 1
88개 1
동상이몽2＿너 1
운명 1
유일 1
건…이영지, 1
투바투 1
수빈, 1
현아 1
샤 1
나연, 1
크러수, 1
방탄 1
학생들 1
&lt;김채원 1
강릉 1
동명중 1
교사&gt; 1
◇AI 1
‘지식’ 1
역설적 1
중요성 1
탄생 1
전환기 1
과감 1
아트랩대전] 1
동물원 1
9월 1
박용화(5월), 1
양승원(6월), 1
양태훈(7월), 1
김들림(8월), 1
김영진(9월), 1
김채원(9월) 1
6명 1
작품세계 1
차례 1
&lt;편집자 1
주&gt; 1
박용화 1
아트랩대전 1
언포기븐…큐트·섹시 1
['홍은채 1
드레스 1
타이츠, 1
슬리브리스 1
팬츠 1
왼쪽 1
시계 1
방향 1
팬츠, 1
오버사이즈 1
벨트 1
토끼…큐티+섹시 1
22 1
“고생했다 1
언포기븐” 1
탐내더니…짱구 1
버전 1
이영지(20) 1
[셀럽이슈 1
['최예나, 1
1994년생 1
2002년생 1
출연진들 1
익숙치 1
['한강 1
열정적 1
김윤 1
달빛 1
무지개 1
피날레 1
키즈까지, 1
간 1
장만 1
‘언포기븐→프시케’ 1
활동곡 1
변경…‘역대급 1
난이 1
퍼포 1
성료…후속곡 1
돌입…역대 1
‘. 1
듀엣 1
내달라 1
윈터X르세라핌 1
비주얼합 1
(+영 1
후렴구 1
발끈해 1
웃음바다 1
3명 1
나눠먹어 1
충분한 1
충격적 1
먹성 1
끓여먹는다 1
놀라움 1
뺏어먹어 1
충격 1
누리꾼 1
에스파·NCT 1
['1(6,922장), 1
5,864장 1
50 1
4장 1
“은퇴 1
이민 1
수준…매장 1
(혜미리예채 1
마무리… 1
카즈하·김채원·허윤진 1
티저 1
강렬 1
떼창 1
1회 1
1무릎 1
실천 1
허당기 1
성료…韓美 1
군무 1
한국·미국 1
마무리→후속곡 1
‘인기가요’를 1
난이도 1
시대…MZ세대→센언니까지 1
봇물[초점S 1
추억 1
아따맘마 1
달빛천사 1
주제가 1
공주 1
옷 1
파티…OTT 1
티빙ㆍ넷플 1
이거 1
챌린지하 1
후배들 1
선물한 1
드시고라 1
['혼밥 1
이유…내 1
‘밥 1
친구’ 1
밥 1
친구 1
소문 1
역대급…무대 1
특별했다…레전드 1
꺾고…5월 1
상위 1
처음 1
스키즈·NCT 1
127→청하X크리스토퍼, 1
일리스 1
스트레 1
143 1
['‘K-909’, 1
모 1
한국기업평판연구소 1
구창환 1
소장 1
세대차 1
자태 1
10순위 1
활약…글로벌 1
베리베리 1
1위(7,056장)… 1
405장 1
세븐틴(Seventeen 1
에스쿱스·정한·조슈아·준·호시·원우·우지·디에잇·민규·도겸·승관·버논·디노) 1
4th 1
SSERAFIM·김채원, 1
['[디패Go] 1
“포기말고, 1
따라해봐”…르세라핌, 1
완전정복 1
일품 1
양손 1
토끼 1
귀 1
소멸 1
직전 1
비하인드컷 1
['슈취타·차쥐뿔·조목밤 1
술토크 1
흥한다[★FOCUS 1
가수들 1
덴마크 1
영역 1
라인업 1
284 1
1800 1
뷰(방탄소년단 1
['강원특별자치도, 1
곳 1
강원특별자치 1
버스 1
['김채원(서울·26) 1
워크숍 1
한번 1
많이했던 1
과격한 1
가사 1
헤드폰 1
여 1
여성미 1
르세라핌이라 1
호랑이 1
반전미 1
대방출…나날 1
독특 1
문양 1
원피스 1
핫팬츠 1
이러 1
매일 1
성수기…왜 1
언제봐 1
별 1
눈동자 1
위해 1
딥 1
키스 1
모닝 1
엔젤 1
자신들 1
패셔너블한 1
출근룩 1
도도 1
츄~ 1
전격 1
상큼발랄 1
가전 1
모델 1
청량감 1
모태 1
큐티엔젤 1
“행복해요”(뮤직 1
“섹시한 1
돼” 1
철통 1
보호(뮤직뱅 1
아래 1
미니팬미팅)[ 1
매력[엑s 1
화보 1
['허윤진·김채원·홍은채, 1
미녀들 1
뮤지뱅크 1
꽃하트 1
만발 1
카즈하(왼쪽부터) 1
['르세라핌-뉴진스, 1
경제 1
나날 1
사랑스러워[★포토 1
김채원·홍은채 1
김채원(왼쪽), 1
뼘 1
미니스커트 1
롱 1
부츠 1
['쏘스뮤직 1
“2년 1
전달할래요 1
”…두산, 1
허윤진-김채원-홍은채,여의도 1
김채원,사랑스런 1
사쿠라-허윤진-김채원,예쁜애 1
허윤진-김채원-홍은채,러블리 1
김채원,상큼 1
김채원,단발 1
여신 1
쌈무[★포토 1
김채원이19 1
김채원,심쿵 1
눈맞춤 1
실화 1
김채원,아침 1
스튜디오 1
큐티&amp;시크 1
엄선해 1
5인5색 1
시크 1
여신[★포토 1
발끝 1
고급미 1
콸콸콸~(뮤직뱅크 1
['더윈드 1
['[포토]허윤진-김채원, 1
체리피스 1
현실감 1
본다… 1
포 1
낫띵(All 1
김채원·허윤진·세일럼 1
에일리·유주·릴리 1
디스 1
이즈 1
미(This 1
심쿵해 1
피어 1
['KBS2 1
포토콜 1
예쁘죠[포토엔HD 1
여친룩 1
청량함 1
섭취주의보 1
스타일리시한 1
표정~[포토엔HD 1
반칙[엑s 1
흔들[엑s 1
없네[엑s 1
['NCT127·르세라핌·스키즈, 1
본능 1
발동 1
잔망 1
가득[엑s 1
['K909, 1
‘무대 1
맛집’ 1
애교 1
만렙 1
햇살 1
찬란한 1
블루 1
셔츠 1
플레어 1
애교포즈 1
에이머스, 1
아이칠린 1
두눈 1
김채원x홍은채, 1
루피 1
예뻐~[포토엔HD 1
감각 1
매장 1
['김윤영·김채원·이지현·홍기정(13), 1
김수빈·박보경·서세영(15), 1
나재연(16), 1
김설송·오민영(17), 1
백지윤(18), 1
김채영(19) 1
학 1
생(31명): 1
하늘·강유민(18), 1
황윤영·김희연(19), 1
김태희·류지애·류현진·이다은·이민서·이승현 1
오픈 1
자정 1
라이센스 1
제약·헬스 1
JW메디칼·삼진제약·현대약품·종근당건강·지멘 1
혼돈 1
드라마틱한 1
['로잘리아 1
환승연애2 1
이지연 1
의미심장한 1
감상평 1
쇼케이스에서 1
관련한 1
유사성 1
코리안심포니 1
수원시향 1
대구시향 1
유수 1
오케스트라 1
풍부 1
관계자 1
연주자들 1
16,040 1
6,427장 1
베리베리(VERIVERY 1
동헌·호영·민찬·계현·연호·용승·강민) 1
‘5월 1
공개…‘걸그룹 1
아트엠콘서트, 1
공개…‘걸 1
‘#UNFORGIVEN’ 1
‘최강 1
퍼포먼스’ 1
공개…전세계 1
성년 1
학폭논란 1
재학중 1
당사 1
지속적 1
최선 1
5명 1
지속 1
의사 1
페이스북 1
나머지 1
카즈하보다 1
안정적 1
톱6 1
7’ 1
합류···정성호-박슬기-황수 1
['‘첼로 1
선율 1
보여준다’ 1
첼로 1
앙상블(ON 1
제2회 1
정기 1
강동혁, 1
김연아, 1
김윤정, 1
성유림, 1
신부 1
이효연, 1
임성채, 1
이민정 1
이창환, 1
장세 1
최영옥, 1
허윤호 1
음악감독 1
첼리스트 1
한국예술종합학교 1
예비학교 1
생일+장군엔터 1
겹경사…장군엔터테인먼트 1
['김의영 1
박슬기 1
박소라 1
['르세라핌/ 1
사진=쏘스뮤직 1
엔터테인먼트 1
[진향희 1
톱7’ 1
트롯 1
전속 1
계약…전폭적 1
아끼 1
['홍자, 1
정다경, 1
강예슬, 1
양지 1
김태연, 1
은가은 1
강아랑, 1
김태술 1
TOP7 1
전속계약…정성호·박슬기 1
공 1
TOP7’ 1
['아이브→르세라핌→에스파→(여자)아이들, 1
전성시대 1
주요 1
유지 1
['뉴진스, 1
르세라핌·피프티피프티· 1
굳히기 1
전속계약…박슬기·고정우 1
이외 1
실시간차트 1
전속계약…새로운 1
6위→멜론 1
신기록→유튜브 1
재생수 1
9억 1
3천 1
전폭 1
불가능 1
마침내… 1
톱100 1
['르세라핌(홍은채·카즈하·허윤진·사쿠라·김채원) 1
음원사이트 1
16 1
신기록→ 1
UNFORGIVEN(언포기븐)(feat. 1
정성호-박슬기-황수경 1
['“꿈 1
이루어졌다” 1
등극…파죽지세 1
차지했다”고 1
등극→美 1
세우더니…멜론 1
‘UNFORGIVEN(언포기븐) 1
전방위적 1
전속계약…박슬기 1
“전폭적 1
지원” 1
전속계약…정성호-박슬기-황수 1
1위(389,369장)…NCT 1
1,027장 1
882장 1
에이머스(AIMERS 1
승현·은준·도륜 1
나혼자 1
산다(전현무·박나래· 1
432개 1
3,368개 1
641,000회 1
114건 1
51개 1
PD수첩(오승훈) 1
전현무…박나래·이장우·유재석 1
새끼 1
오은영(123점), 1
김채원(119점), 1
이영자(104점), 1
런닝맨 1
송지효(100점) 1
그린즈(Grinse)단원(성암초등학교 1
6학년 1
아동기본법 1
며 1
권리 1
때문 1
아동들 1
['“망했다” 1
‘최초’ 1
실패…쉬지 1
(혜미리예채파)[TV종합 1
흥미진진한 1
['【투데이신문 1
강시원 1
유지혜 1
이지예 1
최유진 1
기자】언제부터 1
1980~2000년대생 1
묘사 1
명사격 1
용어 1
삶 1
추구 1
무선 1
아이브·뉴진스·르세라핌·에스파 1
6위…K팝 1
2년 1
팬덤+대중성 1
“행복 1
아이템 1
‘스펀지 1
세트’ 1
호 1
1위…김채원·사쿠라 1
['전소연·김채원·사쿠라, 1
1→3위 1
사진=(여자)아이들 1
데뷔한 1
[송일섭 1
공작 1
무표정한 1
61위 1
200(미국 1
39위 1
전국매일신문 1
이현정기 1
hj_lee@jeonmae. 1
르세라핌,빌보드,언포기븐,김채원,사쿠라,허윤진,카즈하,홍은채 1
6관왕…피어 1
19주차 1
세븐틴·르세라핌 1
TOP5 1
35,159장 1
20,051장 1
원어스(ONEUS 1
레이븐·서호 1
인증 1
['[사진=쏘스뮤직] 1
Rodgers)(언포기븐) 1
겸 1

In [ ]:
pd.DataFrame(text_classifier(["오늘 영화 너무 재미있었어요.", "오늘 영화 정말 별로에요."]))

     label     score
0  LABEL_1  0.749115
1  LABEL_0  0.818968

In [ ]:
result = text_classifier(test_)

In [ ]:
rlt = [int(i['label'][-1]) for i in result]

In [ ]:
### result --> 숫자 뽑아서 리스트로

In [ ]:
rt = ratings_test.head(5000).copy()
print(rt.dtypes)
rt.head()

In [ ]:
rt['fit'] = rlt

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_true=rt['label'], y_pred=rt['fit']))

In [ ]:
### 책에서는 85.52%

In [ ]:
!pip install diffusers

In [ ]:
from diffusers import StableDiffusionPipeline
import torch

model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0]  
    
image.save("astronaut_rides_horse.png")